### ISSUE TITLE
Add to documentation: Consistent usage of "ProbNum" and "`probnum`"

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#101]
The policy regarding usage of "ProbNum" and "`probnum`" seems to be:
- When referencing this package in text, one should use "ProbNum" with capital "P" and "N".
- When referencing this package as the specific piece of software, often in a coding context, one should use "`probnum`", as it appears in the actual Python code when importing the package.

To make sure that this is (and stays) consistent:
- [x] Make sure this is consistent in the current documentation
- [x] Add a statement about this usage *somewhere*

**Comment by nathanaelbosch** [comment]
I actually did not yet encounter an example of wrong usage of "ProbNum" in the documentation, so maybe this is not an issue at all :)

**Comment by JonathanWenger** [comment]
This is fixed in the new documentation and added to the styleguide. Will be closed by #103 .
