### ISSUE TITLE
Dense output for ODE solvers (and potentially filters in general)

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#104]
The ODE solver should, additionally to the discrete solution which it currently outputs, return an `OdeSolution` (name motivated by the [SciPy object of this name](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.OdeSolution.html#scipy.integrate.OdeSolution), but up for debate), which can be called to provide a solution for any point in time `t`.

In implementating such an object for ODE solutions, we might also implement a more general version of this for filters in general, which `OdeSolution` would then call / contain / inherit from.
One difference that comes to my mind is that `OdeSolution` should describe function values, but the generalized object for filters should describe *states*.

I don't have concrete steps for the procedure on this task in mind, and I personally don't know when I would have time for it.
I just wanted to open an issue to properly keep track of ProbNum related tasks ;)

**Comment by pnkraemer** [comment]
I agree with everything. Let's take this up in the next weeks at some point. Some details of what you say I don't understand 100% but seems like it is just a brainstorm anyway so no need to follow up.

**Comment by JonathanWenger** [comment]
From the outside: should this `OdeSolution` object also either contain or inherit from `RandomProcess`?

**Comment by pnkraemer** [comment]
In principle, yes. In my view, it depends on what we think a `RandomProcess` should be.

I've thought about this for a bit and even started implementing one (somewhere there is a lonely `RandomProcess` branch), but I am still not entirely sure about what a RandomProcess would be. Is it a stack of `RandomVariable` objects? Is it something that is described by an SDE or a covariance kernel, i.e. something like a Gaussian process? If it is discrete, can you also describe it with transition densities? 

Other than this (and I am not saying that we shouldn't do `RandomProcess` objects but instead that we probably need to think some more about what we want from them), I think a dense output respectively `OdeSolution` will happen much more quickly than a `RandomProcess`. If at some point we have both, there may be a natural connection so perhaps one can generalise the other.
