### ISSUE TITLE
Use flake8 to better verify PEP 8 compliance

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#108]
This is complementary to using *Black* (#102). There is also overlap with #66. 

### About flake8
[flake8](https://flake8.pycqa.org/en/latest/index.html) checks code compliance to [PEP 8](https://www.python.org/dev/peps/pep-0008/). This is not a duplication to our usage of *Black*: *Black* formats code automatically, but there are code issues that *Black* can not automatically solve, e.g. [wildcard imports](https://docs.quantifiedcode.com/python-anti-patterns/maintainability/from_module_import_all_used.html). flake8 captures these issues.

Sidenote: Trying out flake8 locally seems to raise mostly the following issues:
- line-length (~75%)
- star imports (~10%)
- unused imports (~10%)

There is also a flake8 plugin which I encountered together with flake8 (in the [*Black* repo](https://github.com/psf/black/blob/master/.flake8) actually): [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear). The provided [list of warnings](https://github.com/PyCQA/flake8-bugbear#list-of-warnings) gives me the impression that it overall provides useful feedback.

#### My personal opinion
Cons:
- Yet another tool
- Additional set up requirements for developers
- Another larger code migration

Pros:
- Better code quality through better PEP 8 compliance
- Less work for third-party / beginner PR reviews since feedback on these code quality aspects is given automatically

### Concrete Proposal
- using both flake8 and flake8-bugbear
- adding flake8 to tox, and thus to TravisCI
  (alternatively we could probably also use GitHub Actions)
- adding a pre-commit hook to support that workflow, similar to what I did for `black`

If we chose to do this, then again we will need some form of code *migration* through a larger commit.
I believe that this should best be done right after merging (#102).

**Comment by pnkraemer** [comment]
Can we make black format code according to what flake8 wants? I am mostly thinking about line length. If not it might be weird having to tools that complain about each other.

**Comment by nathanaelbosch** [comment]
> Can we make black format code according to what flake8 wants? I am mostly thinking about line length. If not it might be weird having to tools that complain about each other.

It's rather the other way round: We configure flake8 to accept what Black does :) Black provides an explanation on how to set up flake8: https://github.com/psf/black/blob/master/docs/compatible_configs.md

I also started a branch with the corresponding config files and additions to tox: https://github.com/nathanaelbosch/probnum/tree/flake8. I think that would be quite ready for a PR already (after merging the Black PR #102), except for actually fixing the complaints of flake8.

**Comment by pnkraemer** [comment]
What a pity, I kind of like the shorter lines. Either way, I will be happy as long as those two don't argue :)

**Comment by JonathanWenger** [comment]
**Decision from PN Software Interest Group:**

@nathanaelbosch with help from @marvinpfoertner will decide between `flake8` and `pylint`. Some concrete differences that were discussed are:

- pylint in its base config is stricter than flake8
- pylint cannot ignore single lines (this is relevant e.g. for long lines of math in docstrings)
- pylint longterm enforces better code quality and is more configurable

One suggestion: Configure `pylint` to be not very strict and increase strictness over time (as issues in the codebase are fixed)

**Comment by nathanaelbosch** [comment]
After some more discussion with @marvinpfoertner we decided in favor of pylint. I will start a PR in the coming days.
