### ISSUE TITLE
Implement indexing and reshaping for random variables

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#11]
Indexing, masking and reshaping as is possible for ``numpy`` arrays should be possible for random variables in a similar manner.

**Comment by pnkraemer** [comment]
Maybe---if applicable to more than just the multivariate normal distribution---we could even implement slicing of random variables. I think one needs a `__len__`and `__getitem__`, maybe even only the latter. This would allow extracting univariate gaussians from multivariate gaussians (but I am not 100% sure whether it would be useful and not just some fun functionality, or---in the worst case---even confusing).

**Comment by JonathanWenger** [comment]
We probably also want a transpose operation.
