### ISSUE TITLE
Proposal: Change `update` return signature

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#117]
This time with an issue, instead of commiting and waiting for your comment there ;) Also, this would be a change that requires broader code modifications.

**Motivation:**
Currently, `update` returns `updated_rv, covest, ccest, meanest`. This felt a bit cryptic and hard to understand for me.

**Proposal:**
A few first ideas/proposals on how to improve this:
1. Adding a docstring: This is the obvious improvement and I'll do that independently of the outcome of this discussion
2. Rename variables: I would have proposed `meas_cov`, `crosscov`, and `meas_mean`. The `_est` could be added back of course, but the fact that they describe the "measurement" is useful to me, and `crosscov` is used at other places.
3. Combine `meanest` and `covest` into `measurement_rv`: This would greatly improve the clarity for me. The output would then become `updated_rv, measurement_rv, crosscov`. But, **this would require changes accross many files**, which is why I wanted to discuss first, not after.

**Comment by pnkraemer** [comment]
All valid points, and thanks for bringing this up before changing it. Let's talk about this in person in the next days?

**Comment by pnkraemer** [comment]
> Combine meanest and covest into measurement_rv: This would greatly improve the clarity for me. The output would then become updated_rv, measurement_rv, crosscov.

I agree, lets do this asap(ish) :)
