### ISSUE TITLE
Convenience functions `RandomVariable.var` and `RandomVariable.std`

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#122]
If we want to access the variance and standard deviation often, it might be useful to have those convenience functions. The naming could also be `cov` and `std`, which might be more in line with our current style.

EDIT: I just saw that `Distribution` has those functions. Then I guess my question is: Would it make sense to have those for RVs also? If not, what is the reasoning behind that?

**Comment by JonathanWenger** [comment]
Absolutely. I believe these may have even existed at some point and gotten refactored. I would suggest to have `cov` `var` and `std` such that `cov` returns the covariance, `var` its diagonal and `std` the square root of `var`. For univariate rvs `cov` and `var` return the same.

**Comment by marvinpfoertner** [comment]
This issue should resolve itself if we decide to unify random variables and distributions, right? Relates to #131.
