### ISSUE TITLE
Deprecated `_nsteps` (in statespace.py) and `cke_nsteps` (in {extended,unscented,}kalman.py) ? 

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#126]
While removing `nsteps` from the ODE solver, in favor of the dense output / `ODESolution` object, I saw that there are similar objects around in other files, notably:
- `./src/probnum/filtsmooth/statespace/statespace.py`: `_nsteps`
- `./src/probnum/filtsmooth/gaussfiltsmooth/kalman.py`: `self.cke_nsteps`
- `./src/probnum/filtsmooth/gaussfiltsmooth/extendedkalman.py`: `self.cke_nsteps`
- `./src/probnum/filtsmooth/gaussfiltsmooth/unscentedkalman.py`: `self.cke_nsteps`

I'm not 100% sure of where these are currently used. Should we keep them around, or are they also to be replaced e.g. with the new `KalmanPosterior`?

**Comment by pnkraemer** [comment]
Short answer: they serve a different purpose so they should stay.

Longer answer: `cke_nsteps` is important for the solution of the chapman-kolmogorov equation for all SDEs that are not LTI. If the SDE is only linear (and not linear time-invariant), then the mean and covariance are solutions to respective ODEs and need to be approximated (which is done in LinearSDE.chapmankolmogorov using a simple Euler scheme with `h=(stop-start)/self.cke_steps`. For those SDEs which admit a closed form solution (i.e. LTISDEs) this `self.cke_nsteps` is ignored and only part of the signature to maintain the same API (perhaps it should be set to `step=None` as a default in those cases and explicitly mentioned in the signature that it is ignored? Who knows...).

**Comment by pnkraemer** [comment]
Good question though, I totally understand why it looks like they are the same as the `GaussianIVPFilter.nsteps` variables.

**Comment by nathanaelbosch** [comment]
Thanks for your detailes answer :) 

What about the `_nsteps` argument of `generate_cd` and `generate_dd` in `statespace.py`? If this serves a similar purpose and should also stay we can close the issue.

**Comment by pnkraemer** [comment]
Yes, that is the same variable/idea/purpose/etc..
