### ISSUE TITLE
TravisCI does not seem to run tests with Python 3.6

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#127]
Found this when looking into this build: https://travis-ci.org/github/probabilistic-numerics/probnum/builds/712479064

The Python 3.6 run seems only to run the `docs` tox env, while the 3.7 and 3.8 runs run tests. Not a huge issue, since we're still testing, but this is not the desired behaviour.

**Comment by JonathanWenger** [comment]
Is it possible that this is due to an extra space in the config? From looking at the default `envlist` 
```ini
[tox]
envlist = py3,docs,benchmarks
```
which is executed when I run `tox` locally, should the `travis` environment in `tox.ini` instead of 
```ini
[travis]
python =
  3.6: py36, docs
  3.7: py37
  3.8: py38
```
maybe look more like this
```
[travis]
python =
  3.6: py36,docs,benchmarks
  3.7: py37,docs,benchmarks
  3.8: py38,docs,benchmarks
```
This is also related to #112 and therefore #137 .

**Comment by nathanaelbosch** [comment]
I would not expect it, but yes it could be that the whitespace influences that, I could check that tomorrow. But do we actually want to run docs and benchmarks on all python versions? I would have thought that this is only really relevant for the test suite.

**Comment by JonathanWenger** [comment]
I could imagine cases where the Python version breaks 'asv' functionality or one of the sphinx addons used to build the documentation. But i'm not sure what the best practice is here. Since the builds run in parallel on Travis this shouldn't increase the development loop times much.

**Comment by JonathanWenger** [comment]
Whitespace is not the problem. From a quick google search this seems to be a problem with the `tox.ini` setup for Travis. If i make the suggested change above the docs and benchmarks are run but not the tests for any environment.

**Comment by nathanaelbosch** [comment]
I found something: Adding `py36,py37,py38` to the `envlist` in `tox.ini` resolves this issue (see https://github.com/nathanaelbosch/probnum/commit/e1477eb44924659625845efbd0cc8d3c37f7ffd0 and the corresponding Travis run https://travis-ci.org/github/nathanaelbosch/probnum).

I see two fixes here:
1. Add `py36,py37,py38` back into the envlist again. This however will lead to errors if people just run `tox` to quickly check if things seem fine, but don't have all python versions installed, which is why we moved to just having `py3` in the envlist.
2. Stop using `tox-travis`: I found some examples of projects using tox with travis which we could just recreate (e.g. [flake8](https://github.com/PyCQA/flake8/blob/master/.travis.yml) and [pylint](https://github.com/PyCQA/pylint/blob/master/.travis.yml)), which basically amounts to setting `TOXENV` in the `.travis.yml` file for each different job.

**Comment by nathanaelbosch** [comment]
After a quick chat with @JonathanWenger we came to the conclusion to move from `tox-travis` to adding individual jobs to `.travis.yml`. This way we keep the `py3` env in the `envlist` for slighly more convenience. Additionally TravisCI will then have different jobs for testing, docs and benchmarks which makes it a bit more readable and convenient.
