### ISSUE TITLE
Remove Distribution class and only use RandomVariable with subclasses

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#131]
In the current usage of `RandomVariable` and `Distribution` there is no reason for the existence of two separate classes beyond semantic separation. The current implementation also forces a lot of duplicate implementation of the same functionality in both classes.

Therefore remove `Distribution` and subclass `RandomVariable` with classes like `NormalRandomVariable` instead. This is also closer to an envisioned implementation of `GaussianProcess` inheriting from `RandomProcess`.

**Comment by JonathanWenger** [comment]
The original separation was in part inspired by TensorFlow Probability, where `RandomVariable` is the analogue to a tensor and also a `Distribution` class exists.

https://www.tensorflow.org/probability/api_docs/python/tfp/edward2/RandomVariable
https://www.tensorflow.org/probability/api_docs/python/tfp/edward2/Distribution

**Comment by nathanaelbosch** [comment]
One pylint message that only relates to this part of the code, and that might therefore be fixed as part of this refactoring: `broad-except`.
Check with `pylint src --enable="broad-except"`.
In case you resolve it, please also the exception from the `./pyproject.toml` :)

**Comment by nathanaelbosch** [comment]
Instead of my previous comment: When working on this refactor, it might be useful to look at #159 from time to time, since this issue might resolve some of the current pylint exceptions :)

**Comment by JonathanWenger** [comment]
> Instead of my previous comment: When working on this refactor, it might be useful to look at #159 from time to time, since this issue might resolve some of the current pylint exceptions :)

@marvinpfoertner I assume you have done so, but just to make sure can you do a check in #164 for this?
