### ISSUE TITLE
Use isort to sort the order of import statements

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#140]
While discussing #108 (flake8/pylint) with @marvinpfoertner we also talked about using [isort](https://github.com/timothycrosley/isort) to sort the order of import statements. It seems easy to set up in most popular editors (e.g. VS Code and PyCharm), or it can be used with pre-commit. It makes code more readable. And even if someone is completely unaware of the tool, PR errors could be fixed by installing and running isort (`pip install isort`, and `isort`), or through tox (`tox -e isort`).

It should also be quick to add to probnum.

@JonathanWenger any thoughts?

**Comment by oriash93** [comment]
Would like to take up on that, if possible.

**Comment by JonathanWenger** [comment]
@oriash93 Sure! Contributions are always welcome. Check out the [contributions guide](https://probnum.readthedocs.io/en/latest/development/contributing.html) to get started on a PR.

Regarding `isort`, I think it would be best to have it in `tox`. We can also write a note about `pre-commit` into the "Advanced Developer Setup" section which is added in #181.

**Comment by oriash93** [comment]
> Regarding `isort`, I think it would be best to have it in `tox`.

I added it to `tox` in a similar way to Black.

> We can also write a note about `pre-commit` into the "Advanced Developer Setup" section which is added in #181.

Got it, I will do it separately.
