### ISSUE TITLE
Refactor Normal class to compositional pattern

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#145]
Instead of having a class hierarchy create a single `Normal` class which in its constructor composes different versions of normal by passing different implementations of `sample`, `pdf`, ...

This ensures that
- if `x=Normal(mean, cov)` is called, the type of `x` is `Normal`
- the user does not need to care about different types of normal distributions

The different classes implementing different normal distributions currently only exist to implement efficient sampling, pdf computation, etc. The refactored class would have one large ```__init__``` but the rest of the class is simpler.

**Comment by pnkraemer** [comment]
I am intrigued what comes out because a similar pattern is used in `Kalman`, `ExtendedKalman` and `UnscentedKalman`. I suppose that if it is a clear improvement here, it could be a clear improvement there.
