### ISSUE TITLE
Update styleguide to reference Google style guide

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#147]
- Reference Google style guide and remove redundant (less important) parts. 
- Do not use factory functions wherever possible (alternatively use a class)

**Comment by JonathanWenger** [comment]
Add into styleguide how #todo comments are added. We agreed on allowing todo comments but they need to be associated with an issue. Add a fixed format for todo comments that links to issues (vscode github extension allows direct viewing of issues in the editor).

**Comment by pnkraemer** [comment]
This seems to be done to me. Google styleguide is referenced, and as far as I know, the todos are all in this format by now (even if not, there is a separate issue for this). Please reopen if you consider this not done.
