### ISSUE TITLE
Refactor `probnum.randvars` to resolve the pylint messages

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#159]
At the time of writing, `probnum.randvars` triggers the following `pylint` messages:
- [x] ~~`too-many-instance-attributes`~~
- [x] ~~`broad-except`~~
- [x] ~~`arguments-differ`~~
- [x] ~~`abstract-method`~~
- [x] ~~`too-many-arguments`~~
- [x] ~~`protected-access`~~
- [x] ~~`duplicate-code`~~
- [x] ~~`unused-argument`~~
- [x] ~~`missing-module-docstring`~~
- [ ] `missing-function-docstring`
- [x] ~~`raise-missing-from`~~

__Goal:__
Our long-term goal is to enable all of these checks for all parts of the project. Therefore, we should continuously work on fixing these. Currently, pylint is set up to have different checks for different modules, such that we can work on these problems individually and progress more quickly :)

__To work on this issue__ you can check for these messages individually by calling:
```
pylint src/probnum/prob --disable=all --enable=<message>
```
Then, after fixing all errors/warnings, you should remove the exception from the corresponding line in `./tox.ini`, such that this message will be tracked in the future.

**Comment by marvinpfoertner** [comment]
Most of these points will be resolved by #164.

**Comment by marvinpfoertner** [comment]
Superseded by #523
