### ISSUE TITLE
Refactor `benchmarks` to resolve the pylint messages

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#161]
At the time of writing, `benchmarks` triggers the following `pylint` messages:
- `attribute-defined-outside-init`
- `unused-argument`
- `redefined-builtin`
- `missing-class-docstring`
- `duplicate-code`
- `missing-function-docstring`
It might also be that we do not actually want to fix all of these for the benchmarks, so if you have an opinion on this please share it by commenting on this issue.

__Goal:__
Our long-term goal is to enable all of these checks for all parts of the project. Therefore, we should continuously work on fixing these. Currently, pylint is set up to have different checks for different modules, such that we can work on these problems individually and progress more quickly :)

__To work on this issue__ you can check for these messages individually by calling:
```
pylint benchmarks --disable=all --enable=<message>
```
Then, after fixing all errors/warnings, you should remove the exception from the corresponding line in `./tox.ini`, such that this message will be tracked in the future.

**Comment by pnkraemer** [comment]
see #178

**Comment by pnkraemer** [comment]
Solved in PR #178, hence closed.
