### ISSUE TITLE
Resolve pylint warnings in `probnum.utils`

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#162]
At the time of writing, running `pylint src/probnum/utils` triggers:
- [x] `duplicate-code` fixed by #233 
- [ ] `missing-module-docstring`
- [ ] `missing-function-docstring`

After fixing all these errors/warnings, or after adding exceptions for these in the files, please remove the corresponding exception from `./tox.ini`, such that this message will be tracked in the future.

**Comment by pnkraemer** [comment]
See #204.
