### ISSUE TITLE
Observation RMSE does not reflect true observation error

### ISSUE THREAD

**Issue by marvinpfoertner** [probabilistic-numerics/probnum#165]
As discussed in person,

https://github.com/probabilistic-numerics/probnum/blob/0f7877bc4cfa7deab10d815519966cbe87b29dc3/tests/test_filtsmooth/test_gaussfiltsmooth/test_unscentedkalman.py#L207

should be changed to `obs_rmse = np.linalg.norm(self.obs[:, 0] - comp[1:]) / normaliser`. Possibly also for EKF.

**Comment by pnkraemer** [comment]
Solved in #167
