### ISSUE TITLE
PN method tutorial and prototypical Implementation

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#175]
Create a PN tutorial which step-by-step explains with an example of what a PN method is, what it consists of and the type of problem it solves. Secondarily, reference this method in a detailed sample explanation with type hints, observations/actions, policy, stopping criteria, class structure, convenience function signature extra.

**Detailed Example:**
- noisy quadratic optimization of a 1D example: (a+e_a)x^2+(b+e_b)x+c+e_c = f(x) = \hat{y}
- results in a 1D example of the PLS
- plot the quadratic and its quantiles in a plot to illustrate the problem
- show iterations of the solver (1D belief over x-axis with true quadratic and sample quadratic)

**Development Tutorial:**
- convenience function with type hinted signature and method selection, callbacks, etc.
- Actual class with implementation of PN Method in compositional pattern
- Step-by-step implementation of class components (maybe referenced from detailed example) which outlines policy, stopping criteria, iteration (__iter__?) etc.

**Comment by pnkraemer** [comment]
Controversial take: wouldn't it perhaps be easier to 1) showcase and 2) understand if this prototypical implementation is explained with actual code examples, e.g. linear solver of ODE solver? I don't have a strong opinion on this, but it might be worth thinking about?

**Comment by JonathanWenger** [comment]
It will feature code examples, but they are not production code - at least not in the examples. It's much harder to read code of the actual repository for the average user than a simple (potentially inefficient) example. The development tutorial will still consider the simple 1D example (which essentially is a version of the PLS), but will serve as a template for developers, hence feature production style code.

**Comment by pnkraemer** [comment]
hmmm sounds reasonable. I guess I will wait for the result and then think about it :)
