### ISSUE TITLE
Make `LinearOperator`s more similar to `ndarrays`

### ISSUE THREAD

**Issue by marvinpfoertner** [probabilistic-numerics/probnum#196]
* [x] Currently, `LinearOperator`s sometimes have `linop.dtype == None`. Having a fully specified dtype is important for internal consistency e.g. in the `Normal` random variable.
* [x] Ideally, we should also offer an `astype` method to allow for type casting which is also needed in `Normal`.
* [x] `ndim` and `size` should be added as convenience properties to allow for less complicated code

**Comment by JonathanWenger** [comment]
Also operations like `.trace()` should be similar to numpy in the sense that one can call `pn.trace(linop)` and `pn.trace(ndarray)`, which then calls either `linop.trace` or `np.trace(ndarray)`.

**Comment by JonathanWenger** [comment]
This was implemented in #326 and #381. Any functions similar to `pn.trace`, if necessary can be added via a new issue + PR.
