### ISSUE TITLE
`pylint` should be run on the whole package

### ISSUE THREAD

**Issue by marvinpfoertner** [probabilistic-numerics/probnum#197]
Currently, `pylint` is only run on individual subpackages of `probnum`.
Unfortunately, things like cyclic imports between these packages can't be found unless `pylint` is run on the whole package.
We should run pylint on the entire package using a reduced set of messages to catch more errors.

FYI @nathanaelbosch

**Comment by nathanaelbosch** [comment]
Since we keep the full pylint config up-to-date in the `./pyproject.toml` it should be sufficient to just perform an additional `pylint src` run as a part of our CI, is that right? Or do you suggest running it with different settings?

**Comment by marvinpfoertner** [comment]
> Since we keep the full pylint config up-to-date in the `./pyproject.toml` it should be sufficient to just perform an additional `pylint src` run as a part of our CI, is that right? Or do you suggest running it with different settings?

I agree, I think out `pyproject.toml` settings should suffice

**Comment by marvinpfoertner** [comment]
Superseded by #523.
