### ISSUE TITLE
Implement more `RandomVariables`

### ISSUE THREAD

**Issue by marvinpfoertner** [probabilistic-numerics/probnum#200]
Currently, we only have `Dirac` and `Normal` random variables.
Ideally, at some point, we implement a whole zoo of random variables as e.g. in `scipy.stats`.
Some important candidates are:
- [ ] `Categorical` and/or `Multinomial` (I know @pnkraemer would be happy about these for his SMC code)
- [ ] `Wishart` or `RandomSPDMatrix` which is needed in the tests of `Normal` for generating covariance matrices

**Comment by marvinpfoertner** [comment]
@JonathanWenger @pnkraemer @nathanaelbosch Maybe you have some additional requests?

**Comment by pnkraemer** [comment]
Categorical RVs would be neat but there is no urgency. 

Implementing distributions other than Normal and Dirac will also help to make sure that the interfaces are not overfitted to Normals and Diracs, even though they might not be needed straightaway.

**Comment by pnkraemer** [comment]
Categorical RVs are introduced in #353.

**Comment by JonathanWenger** [comment]
Closing this since there is no concrete way forward. Feel free to create new issues for specific requests for random variable implementations.
