### ISSUE TITLE
Allow joint sampling from ODE solutions

### ISSUE THREAD

**Issue by philipphennig** [probabilistic-numerics/probnum#208]
psol  = probsolve_ivp(...) currently returns a list of RVs. It's possible to plot the sequence of means of these RVs by calling psol.y.mean(). But as far as I can see, one can not draw a joint sample? 

Note that this is not simply a syntax issue: a loop over psol.y[i].sample() doesn't do the right thing, because it returns independent samples, rather than one joint trajectory.

**Comment by pnkraemer** [comment]
See p. 266 of Applied SDEs. While we're at it, it might be nice to be able to build the full covariance matrix if desired (explained on p. 266 as well).
