### ISSUE TITLE
Matrix-matrix multiplication for Kronecker products is slow

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#210]
# Problem
Matrix-matrix multiplication for Kronecker products is slower than expected, in fact slower than dense multiplication.

# Reproducible Example
```python
import timeit
from probnum.linalg.linops import Kronecker, Identity

m = 7
n = 3
block = np.random.uniform(size=(n, n))
kron = Kronecker(Identity(n), block) # block-diagonal matrix
kron_dense = kron.todense()

%timeit (kron_dense @ kron_dense)
> 925 ns ± 5.35 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit (kron @ kron)
> 13.2 µs ± 164 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

# Probable Cause
This could be due to the fact, that `Kronecker` does not actually implement `__matmul__` but relies on the default implementation of `LinearOperator` which loops over matrix-vector products. This is clearly inefficient.

# Suggested Fix
- [x] Implement `__matmul__` relying on the rules for Kronecker product multiplication.
- [x] Add benchmarks for commonly used `LinearOperators`

**Comment by pnkraemer** [comment]
Sorry to chime in, but I have a question regarding this.

Do you think it would be a good idea to do some kind of `LinearOperator` benchmarks? I guess it would be good to set fixes to those kinds of issues in stone. But I am not sure how exactly... Maybe a good starting point would be to do something like (the following is not working python code, but you will get the meaning) `self.assertNotEqual(kronecker.__matmul__, super(kronecker).__matmul__` even though this seems a bit inelegant... 

I would like to have benchmarks for those foundational operations, but there might be many, much more important issues...

**Comment by JonathanWenger** [comment]
Yes benchmarks for linear operators are definitely on the todo list. So are arithmetic operations between different types of Kronecker products, i.e. adding two `Kronecker` operators gives back a `Kronecker` operator as opposed to a `_SumLinearOperator`. 

I am not sure I understand what you mean with the assert statement.

**Comment by pnkraemer** [comment]
> I am not sure I understand what you mean with the assert statement.

An attempt at writing a test that checks whether `Kronecker` has its own matmul implementation and does not steal from LinearOperator anymore. Don't take this too seriously though...

**Comment by JonathanWenger** [comment]
I think the cleaner way to do this would be to simply write a benchmark for linear operators which times matrix-vector and matrix-matrix products. This way any regressions can be easily identified. The test you're describing, assuming I understand correctly, simply tests whether the function `matmat` exists in `linops.Kronecker`. This doesn't seem necessary to me.

**Comment by marvinpfoertner** [comment]
I believe the difference in performance is largely due to problem size. With the newest master, I get

```python
> import timeit
> import numpy as np
> from probnum.linops import Identity, Kronecker
> n = 3
> block = np.random.uniform(size=(n, n))
> kron = Kronecker(Identity(n), block)  # block-diagonal matrix
> kron_dense = kron.todense()
> %timeit (kron_dense @ kron_dense)
4.91 µs ± 21.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
> %timeit (kron @ kron_dense)
55.8 µs ± 487 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

but

```python
> import timeit
> import numpy as np
> from probnum.linops import Identity, Kronecker
> n = 10
> block = np.random.uniform(size=(n, n))
> kron = Kronecker(Identity(n), block)  # block-diagonal matrix
> kron_dense = kron.todense()
> %timeit (kron_dense @ kron_dense)
30.9 s ± 1.34 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
> %timeit (kron @ kron_dense)
10.9 s ± 775 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

and further optimizing the memory layout yields

```python
> import timeit
> import numpy as np
> from probnum.linops import Identity, Kronecker
> n = 10
> block = np.random.uniform(size=(n, n))
> kron = Kronecker(Identity(n), block)  # block-diagonal matrix
> kron_dense = kron.todense()
> kron_dense_f = kron_dense.copy(order="F")
> %timeit (kron_dense @ kron_dense_f)
28.9 s ± 1.35 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
> %timeit (kron @ kron_dense_f)
6.32 s ± 383 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

@JonathanWenger @pnkraemer would you consider this issue resolved?

**Comment by JonathanWenger** [comment]
Yes I do! Thanks a lot.
