### ISSUE TITLE
`method_callback` is applied after storing the results, but the description says otherwise

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#241]
The `method_callback` docstring:
```python
        """
        Optional callback. Can be overwritten.
        Do this as soon as it is clear that the current guess is accepted, but before storing it.
        No return. For example: tune hyperparameters (sigma).
        """
```
But, in `solve` it is used as
```python
            if steprule.is_accepted(stepsize, errorest):
                self.num_steps += 1
                t = t_new
                current_rv = proposed_rv
                times.append(t)
                rvs.append(current_rv)
                self.method_callback(
                    time=t_new, current_guess=proposed_rv, current_error=errorest
                )
```

Should the docstring be adjusted or the order in `solve`? @pnkraemer

**Comment by pnkraemer** [comment]
I think the order should be adapted. This way, one can implement stochastic perturbations in ~ a single line of code (@NinaEffenberger). 
Tbh, when I spoke about this with Nina yesterday I was a bit confused about the order, too, because I remember implementing this method callback with stochastic perturbations in mind. Would you fix this @nathanaelbosch ? I would be thankful for that!

**Comment by nathanaelbosch** [comment]
Sure I can try to fix that, but I guess to enable callbacks that perturb the current estimates there need to be more changes than just the order of these lines. Right now the `method_callback` does not return anything and can therefore not really modify anything else than `self`. Do we want to store the "current guess" in `self` and thereby allow the callback to modify things, or would you rather do that with inputs and outputs to the function?

**Comment by nathanaelbosch** [comment]
But I guess the order can be changed by moving around a few lines, resolving this issue, and we could maybe create a proper issue to discuss desiderata for the callbacks in general?

**Comment by pnkraemer** [comment]
> But I guess the order can be changed by moving around a few lines, resolving this issue, and we could maybe create a proper issue to discuss desiderata for the callbacks in general?

Good idea.
