### ISSUE TITLE
Diffeq: Proportional step size control with both absolute and relative tolerances

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#247]
The step size controller which is implemented right now does not support relative tolerances. Ideally we would like to have a controller which closely corresponds to the proportional control algorithm described in Hairer's _Solving Ordinary Differential Equations I_. For a more practically oriented referece see also https://diffeq.sciml.ai/stable/extras/timestepping/.

This topic is closely related to error estimation. In total, the steps are the following:
- Estimate a d-dimensional local error
- Scale this d-dimensional error elementwise, considering the absolute and relative tolerances
- Compute a scalar norm of this scaled local error, typically `E = np.sqrt(np.sum(err**2)/length(err))`
- Reject if E>1, accept otherwise
- Compute the new step, as done currently in `AdaptiveSteps.suggest` (without scaling once more with `tol_per_step`)

__The main question here:__ For each of these elementary steps above, where exactly in the code should they happen? Which of them are in `step`, `_estimate_local_error`, `AdaptiveSteps`, or in `solve`?

**Comment by pnkraemer** [comment]
One other change related to `StepRule`: I'd move `firststep` into it as well, and create new attributes `minstep` and `maxstep`. 

As to your question, I am not entirely sure. My initial guess would've been:

> Estimate a d-dimensional local error

In the solver, because this is likely different for each.

> Scale this d-dimensional error elementwise, considering the absolute and relative tolerances
> Compute a scalar norm of this scaled local error, typically E = np.sqrt(np.sum(err**2)/length(err))

The best place of this is not clear to me. In principle, this is the same for every adaptivity, right? Though to me, it seems like more of a steprule concept, because `E` is tied very closely to the next suggestion step and this way we could ensure that they match. My opinion is not set in stone, though.


> Reject if E>1, accept otherwise
> Compute the new step, as done currently in AdaptiveSteps.suggest (without scaling once more with tol_per_step)

I think this belongs to the steprule, as the last one is different for different control strategies (PI, etc.). 
For reference, below is the proportional control code I used recently. I am not sure how optimal this is, but it does a job :) 

> 
> class ProportionalControl(pnd.StepRule):
>     """Adaptive step size selection based on proportional control."""
> 
>     def __init__(
>         self,
>         atol,
>         rtol,
>         localconvrate,
>         limitchange=(0.2, 5.0),
>         safetyscale=0.9,
>         firststep=1.0,
>         minstep=1e-24,
>         maxstep=1e8,
>         **kwargs
>     ):
>         self.atol = float(atol)
>         self.rtol = float(rtol)
>         self.safetyscale = float(safetyscale)
>         self.firststep = firststep
>         self.localconvrate = float(localconvrate)
>         self.limitchange = limitchange
>         self.minstep = minstep
>         self.maxstep = maxstep
> 
>     def suggest(self, laststep, errorest, **kwargs):
>         small, large = self.limitchange
>         ratio = 1.0 / errorest
>         change = self.safetyscale * ratio ** (1.0 / self.localconvrate)
>         if change < small:
>             step = small * laststep
>         elif large < change:
>             step = large * laststep
>         else:
>             step = change * laststep
>         if step < self.minstep:
>             raise RuntimeError
>         if step > self.maxstep:
>             raise RuntimeError
>         return step
> 
>     def is_accepted(self, proposedstep, errorest, **kwargs):
>         return errorest < 1.0
> 
>     def accumulated_error(self, all_errors, y_now, y_last):
>         """Returns E."""
>         eps = self.atol + self.rtol * np.maximum(np.abs(y_now), np.abs(y_last))
>         assert len(eps) > 1
>         ratio = all_errors / eps
>         return float(np.sqrt(ratio.T @ ratio / len(ratio)))
>

**Comment by pnkraemer** [comment]
I think the following is related:

I'd be in favour of letting each ODESolver have an `order`, in which case the `localconvrate` choice can be automatised. This would require less mental RAM on the user's side. Further, I'd bluntly claim that there is always a single **correct** choice (order + 1) and many wrong choices (all but order + 1) for localconvrate. 

Nina also mentioned earlier (and I agree with this) that it is at best cumbersome, at worst error-prone, to not handle `firststep` in `StepRule`. For constant steps, for instance, this should always be the *constant step*.

**Comment by nathanaelbosch** [comment]
Regarding `firststep`:
> One other change related to StepRule: I'd move firststep into it as well, and create new attributes minstep and maxstep.
> Nina also mentioned earlier (and I agree with this) that it is at best cumbersome, at worst error-prone, to not handle firststep in StepRule. For constant steps, for instance, this should always be the constant step.

I might have a different point of view on this, but maybe we mean the same thing: I'm in favor of removing the "firststep" argument and replace it just with "step". I don't think the constant step rule needs to explicitly think about some *first* step, and could just `suggest` whatever is passed as `laststep`. If `tol` is set, `step` could still be used to perform the first step on the ODE (maybe with some smarter selection if `step is None`).

What do you think?


>> - Estimate a d-dimensional local error  

> In the solver, because this is likely different for each.

I agree.

>> - Scale this d-dimensional error elementwise, considering the absolute and relative tolerances
>> - Compute a scalar norm of this scaled local error, typically E = np.sqrt(np.sum(err**2)/length(err))

> In principle, this is the same for every adaptivity, right?

Yes I think so, at least for the forseeable time I don't think anyone will want to experiment with using a different norm function.

> Though to me, it seems like more of a steprule concept, because E is tied very closely to the next suggestion step and this way we could ensure that they match. My opinion is not set in stone, though.

I'm a bit torn here. I like passing `E` to the `StepRule`, not some d-dim error estimate together with the last function estimates for scaling things etc, but I might be a bit biased due to what I'm used to do in the DiffEq.jl context. If we want `PropotionalControl` to hold the tolerance parameters etc it might indeed make sense to implement the scaling and normalizing in there, too. The constant step rule does not require that part anyways. Maybe that's also the simplest way of implementing things for now, and if we add PI-control later (which also requires these tools) we could refactor them out?


>> - Reject if E>1, accept otherwise
>> - Compute the new step, as done currently in AdaptiveSteps.suggest (without scaling once more with tol_per_step)

> I think this belongs to the steprule, as the last one is different for different control strategies (PI, etc.).

I aggree.

**Comment by pnkraemer** [comment]
> I might have a different point of view on this, but maybe we mean the same thing: I'm in favor of removing the "firststep" argument and replace it just with "step". I don't think the constant step rule needs to explicitly think about some first step, and could just suggest whatever is passed as laststep. If tol is set, step could still be used to perform the first step on the ODE (maybe with some smarter selection if step is None).

something along those lines, yes. Let's continue discussing this when we have code.

> I'm a bit torn here. I like passing E to the StepRule, not some d-dim error estimate together with the last function estimates for scaling things etc, but I might be a bit biased due to what I'm used to do in the DiffEq.jl context. If we want PropotionalControl to hold the tolerance parameters etc it might indeed make sense to implement the scaling and normalizing in there, too. The constant step rule does not require that part anyways. Maybe that's also the simplest way of implementing things for now, and if we add PI-control later (which also requires these tools) we could refactor them out?

I'd say it is important the the `step()` method returns a state and a d-dimensional error estimate (which is important for the Conrad-style solvers). Turning this into E can either happen in the `solve()` method directly, before passing this E on to `StepRule.suggest` or something; or in some method in `StepRule`, which is then called in `solve`. I dont think I have a preference and in fact, both options seem super similar. As long as the signature of `step` remains the same, I am happy :)

**Comment by pnkraemer** [comment]
If this is changed appropriately we should also get rid of `ODESolver._suggest_step` which does nothing but call `StepRule.suggest` and print a warning if the step is small.
Desired behaviour is that too small of a step is captured in an Exception inside `StepRule.suggest`

**Comment by pnkraemer** [comment]
If you don't mind, I will get started with this issue now.

**Comment by pnkraemer** [comment]
One thing I will also do (unless you complain) is give each ODESolver an `order`. E.g., RK45 has order 5. This will remove the `localconvrate` choice from Adaptive step rules.

**Comment by nathanaelbosch** [comment]
Sure! I also still think that givin a solver an `order` is a very good idea :+1:
