### ISSUE TITLE
Encapsulate dependencies used only for specific small parts of ProbNum

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#250]
Currently we depend on GPy only for a calibration functionality in `probnum.linalg.problinsolve` similarly the probabilistic ODE solver requires computation of k derivatives of a function at the initial value via automatic differentiation. The dependencies on packages these specific usages introduce should be encapsulated.

One way to do so would be to wrap these usages similar to this:

```python
def calibrate_using_gpy(*args):
    try:
        import GPy
        ...
    except ImportError:
        raise ImportError("Calibration using Gaussian processes requires the optional dependency GPy. Install with pip install GPy.")

````

One could even make the packages [optional dependencies](https://stackoverflow.com/questions/6237946/optional-dependencies-in-distutils-pip) so one could install ProbNum with `pip install probnum[full]`. Packages like `GPy`, `jax`, `matplotlib`, `Cython`, etc. could be used this way.

The advantage of this are:
 - packages soon to be removed are easily swapped out by simply replacing the corresponding function
 - new dependencies are not immediately introduced to the entire package reducing the risk of [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell)

**Comment by JonathanWenger** [comment]
This would serve as a first step to resolve #35 .

**Comment by pnkraemer** [comment]
I think encapsulating GPy like this is a good first step either way! If we write the functions that need jax (currently, there is no jax anywhere near `diffeq`) we can follow the same pattern. This way things can get removed cleanly if necessary.

Making them optional dependencies is a possible step, too, though that is a much bigger decision to make.
