### ISSUE TITLE
Method signatures of filters and transitions

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#251]
I find it inconvenient that `Kalman.predict()` has the signature `start, stop, rv, ...` whereas `transition_rv` has the signature `rv, start, stop, ...`. This is weird and kind of defeats the purpose: in non-iterated filtering, `predict` merely calls `dynamod.transition_rv` thus the function content is only re-ordering? 
The same holds AFAIK for `filter_step`, `measure`, and `update`. In the future I guess this will be extra annoying, because we need to be able to use `Kalman` as a proposal density for particle filters.

**Comment by nathanaelbosch** [comment]
Just to clarify, do I understand you correctly that this issue is only about the order of the function arguments, not the arguments itself? In any case, I completely agree that it is inconvenient that the order differs.

**Comment by pnkraemer** [comment]
Yes
