### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#257]
Travis CI recently came under new ownership and has announced limitations to the number of builds one can perform for open-source repositories. This will eventually stop us from using our CI toolchain. To prevent this ahead of time we need to migrate to Github Actions as soon as possible.

**Comment by JonathanWenger** [comment]
See also: https://developer.okta.com/blog/2020/05/18/travis-ci-to-github-actions

**Comment by Yagueteiro** [comment]
Hi, are you open to contributions?

**Comment by JonathanWenger** [comment]
Absolutely! Feel free to make a pull request. You might find the [Developer Guidelines](https://probnum.readthedocs.io/en/latest/development/contributing.html) helpful.

**Comment by Yagueteiro** [comment]
Hi, sorry for the delay, I've been a bit busy but found some time to look at it. 

I've created a workflow for github actions and it runs Tox, but in the docs part, when it runs CMake it crashes with a `could not find executable make`. I've been wondering around, and found that maybe it's easier to get rid of tox, as I think it can be solved by using the github actions' steps

**Comment by JonathanWenger** [comment]
We rely on `tox` heavily to unify local development with CI builds so getting rid of it is not an option for us. When making related changes I ended up having to do the migration to Github Actions as a necessary step. Feel free to take a look at the PR #275 and offer feedback. Thanks for taking a look!
