### ISSUE TITLE
Exposing testing functions

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#259]
Auxiliary functions for testing are in `tests.testing` and imported in the tests via `from tests.testing import chi_squared_statistics`. 
One thing we may want to discuss is whether we want to move them to `src`. 
This is not urgent, but may be useful for the following reason: Currently, @NinaEffenberger uses probnum for her MSc thesis, would like to use the test statistics for her tests, but cannot import them because there is no way of accessing the `tests.testing.statistics` module.

AFAIK, numpy exposes tests via `numpy.testing`. What do we think about this  (@JonathanWenger, @nathanaelbosch, @alpiges  @marvinpfoertner, @schmidtjonathan)? Do you guys have opinions on this matter?

**Comment by marvinpfoertner** [comment]
I don't see any particular reason not to do this. Just maybe as an additional idea: Did you also consider putting them inside an own package, maybe `probnum-testing` inside `src` and adding this as a test dependency to `probnum`s tests. This would also the nice side effect of making dependencies transparent.

**Comment by JonathanWenger** [comment]
I am a little more hesitant. Are there likely to be more such functions similar to `assertArray*` functions in `NumpyAssertions`? Can we assume people implementing their own package _using_ ProbNum will need tests of the form `assertPNMethod*?

For Nina's case specifically and thesis students in general. What is the advantage over just working in their own fork of ProbNum, where they can use these functions for writing tests? This would also enourage PRs at the end of the thesis and integrate those tests into the main codebase.

**Comment by pnkraemer** [comment]
even though I like the `AssertAllClose` unittest-numpy wrappers, I had the  `statistics` module and potential future extensions thereof in mind. It is hard to test eg. sampling algorithms, so it would be great to do it well once, extract functions, and be able to reuse them wherever (in any of my future projects, not necessarily just in those that will end up in probnum code). 

> For Nina's case specifically and thesis students in general. What is the advantage over just working in their own fork of ProbNum, where they can use these functions for writing tests? This would also enourage PRs at the end of the thesis and integrate those tests into the main codebase.

We are doing it in a separate repo, instead of a probnum fork, because we will do much more than what will end up in probnum. The plan is to try a few things, dissect what is useful (and merge this into probnum) and discard what is not (which will then be buried forever). 

I am not sure what my personal opinion is, so thanks a lot for your feedback!

**Comment by JonathanWenger** [comment]
#### Decision from Software Meeting

Create a (hidden) subpackage `_testing` which contains functions like `chi_squared_statistics` but NOT `assertArray*` statements which are wrappers of `numpy.testing` and used only internally for testing ProbNum. This allows PN method specific testing functions to be exposed for people who write a package (implementing a new PN method for example) but do not (yet) want to do this in (a fork of) the main package.

**Comment by pnkraemer** [comment]
**New decision from the software meeting:**

An (at most test)dependency on ProbNum-Evaluation could be used inside the tests. In this case, we must make sure that changes in ProbNum-Evaluation must not break tests in ProbNum, for instance by running the respective tests as part of the ProbNum-Evaluation CI.

**Comment by JonathanWenger** [comment]
Closing due to no immediate clear action. Feel free to reopen if necessary.
