### ISSUE TITLE
Dimension property in transitions

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#266]
Many `Transition` objects have a property `dimension`, which is useful, though hard to compute without evaluating dynamics vector fields. In this context, we have no idea a-priori where to evalute them reliably, since e.g. `SDE` does not come with initial values.

A similar problem applies to `ODE` children, though since an initial value is provided here, it is reliable to evaluate the function.

A related problem is that some discrete transitions have no clear dimension, because they may map a 4-dimensional state to a 2-dimensional measurement state, in which case the dimension could be either 4 or 2...

**Comment by nathanaelbosch** [comment]
Your example about measurements suggests to me that we should have two different dimensions (`from_dim` and `to_dim` or something). Or what about a tuple?

Other than that it seems to me that we need to either (i) ask explicitly for dimensions in init, (ii) ask explicitly for a value at which it is safe to evaluate, or (iii) just risk it and evaluate at some arbitrary point.

**Comment by pnkraemer** [comment]
resolved in #316
