### ISSUE TITLE
Merge existing code for differential equations

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#27]
TODOs:
- [ ] move code and devise structure
- [ ] compare interfaces of `RandomVariable` classes
- [ ] run tests

**Comment by pnkraemer** [comment]
I already started comparing the interfaces (I think it is good to talk about most post in person tomorrow). 

The RandomVariable interface has one major difference:
Is there a reason why you have a separate `Distribution` object next to the `RandomVariable` object? It seems like the random variable "steals" most of its functionality from the distribution.

**Comment by pnkraemer** [comment]
(Note: I raise a new Issue regarding merging the diffeq code, because there will be multiple "levels" of merging and each one is standalone)

**Comment by JonathanWenger** [comment]
This issue is now redundant as #29 , #30, #31 exist.
