### ISSUE TITLE
API of `probsolve_ivp` 

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#272]
We might want to improve some parts of `probsolve_ivp`:
- Default values for `atol` and `rtol`: I believe we should have some sensible default values
- Explicit argument to choose the steprule: I think that would be cleaner than inferring it from `atol`/`rtol` or `step` being set

**Comment by pnkraemer** [comment]
potentially wild suggestion: how about we get the square root and initialisation in order and then remove the constant step option entirely from probsolve_ivp? That would also communicate some nice new confidence in the solver :)
