### ISSUE TITLE
Choice of `firststep` for adaptive step sizes

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#273]
Currently we choose `firststep = ivp.tmax - ivp.t0`. This seems to work well, but I'm wondering if we could use a better default here. My intuition for example is that we might prefer starting small and getting larger, in order to reduce rejections.

If we want to put in more effort, there is also a page about "Starting Step Size" in "Solving Ordinary Differential Equations I" by Hairer et al, p. 169.

**Comment by pnkraemer** [comment]
> If we want to put in more effort, there is also a page about "Starting Step Size" in "Solving Ordinary Differential Equations I" by Hairer et al, p. 169.

Thanks for the pointer. Lets go for this. We can start with choosing `firststep = 0.01 * norm(y0) / norm(dy0)` which takes 1 minute to implement and then move on the the more involved thing if we like. Do you suggest removing `firststep` entirely, i.e. doing the  `step = 0.01 * norm(y0) / norm(dy0)` in the solver or do you suggest keeping firststep as an argument to e.g. StepRule or solve, but having this sensible default in probsolve_ivp?

**Comment by nathanaelbosch** [comment]
I would have thought that keeping firststep makes sense, but using this to initialize it in probsolve_ivp in the case that it's not set. But then I don't know if I would personally ever set it to a different value, so if you prefer just setting it like this in the solver that could also make sense (and it would be even easier and faster to implement)

**Comment by pnkraemer** [comment]
Maybe we keep it as a somewhat "dead" variable, cause who knows, maybe someone smarter than us wants to use it, who actually knows what to put in there :)

**Comment by pnkraemer** [comment]
Kind of (?) resolved in #269

**Comment by nathanaelbosch** [comment]
It's still initialized in the same way, right? If we want to initialize it in a better way (whatever that means) then I'd keep this open, but if we don't change anything in the forseeable future anyways it's simpler to close this for now.

**Comment by pnkraemer** [comment]
If nothing is provided, we use 0.01 |y| / |dy| now. other than that, not a lot changed.

**Comment by pnkraemer** [comment]
Other than that, I will have to admit that I do not consider making this better a high priority... so we might as well close it if you dont either :)

**Comment by nathanaelbosch** [comment]
Wow I didn't realize that change, I'm a bit unsure about my reviewing qualities now... But that sounds great, let's close this :)

**Comment by pnkraemer** [comment]
We do this now somewhere in `probsolve_ivp`:

```python

    if step is not None:
        stprl = steprule.ConstantSteps(step)
    else:
        if firststep is None:
            # lazy version of Hairer, Wanner, Norsett, p. 169
            norm_y0 = np.linalg.norm(ivp.initrv.mean)
            norm_dy0 = np.linalg.norm(ivp(ivp.t0, ivp.initrv.mean))
            firststep = 0.01 * norm_y0 / norm_dy0
        stprl = steprule.AdaptiveSteps(firststep=firststep, atol=atol, rtol=rtol)
```
