### ISSUE TITLE
ProbNum Logo can not be seen in dark mode

### ISSUE THREAD

**Issue by nathanaelbosch** [probabilistic-numerics/probnum#277]
I just tried out the new dark mode of github (it's nice, if you like dark modes). Unfortunately the PN logo in our README.md kind of disappears then. So if anyone is motivated to play around with graphics, we might want a dark-mode-safe version of our logo at some point :)

**Comment by pnkraemer** [comment]
haha what an issue :D

**Comment by JonathanWenger** [comment]
The new logo is, while not perfect, more visible in dark mode. There are ways to use the SVG version of our logo to actually switch from the dark to the light version (see https://github.com/jamiebuilds/dark-mode-github-readme-logos), however currently this seems unnecessary overhead. In particular in light of GitHub planning to support theme context in Readme's sometime in the future (see https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/58).
