### ISSUE TITLE
Group core functionalities together 

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#28]
Move `randomvariable` into an `auxiliary/` or `core/` directory (naming open for suggestions). 

There will be many more auxiliary modules in the future (e.g. `covariance` or some utility `quadrature` object which is not PN-quadrature) which one should be able to get in one go.

**Comment by JonathanWenger** [comment]
Decided on structure in #36. 

`covariance` should probably be under `prob` or `linalg.linops`.
