### ISSUE TITLE
(Statespace) models

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#282]
Currently, transition rules and the like are in `filtsmooth.statespace`. I'd like to pull them out and make them their own thing. In this context, I think it might be interesting to rename it from `statespace` to something like `models` (as in: *probabilistic models*) because all those transitions can essentially be used as likelihoods for all kinds of things. 

Maybe at some point, we will be able to remove the filtsmooth dependency from `diffeq` and only have a `statespace` (`models` resp.) dependency.

Thoughts on the renaming, @nathanaelbosch @JonathanWenger ? I guess no one would complain about moving it up...

**Comment by JonathanWenger** [comment]
I'm fine with naming it `probnum.models`. Alternatively `probnum.likelihoods` would also be a valid choice I think.

**Comment by pnkraemer** [comment]
I dont think `likelihoods` fits, because there are also components of prior models. Thanks for the suggestion though, it is good to reconsider names :)

**Comment by pnkraemer** [comment]
I am starting to think that `Markov` might be a fun name here... after all, `Transition` objects implement Markov transition kernels.
