### ISSUE TITLE
Build notebooks in CI

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#295]
Currently the tutorials in jupyter notebook form are not run when changes are made. This can cause breaking changes in the tutorials. 

### Suggestion
Move tutorials build into a separate tox command `tox -e tutorials` and add this to the CI

**Comment by pnkraemer** [comment]
**Decision from the meeting:**
Create a separate Github-check which runs all `.ipynb` files in `/docs/source/tutorials` just via nbconvert and checks whether notebooks compile.
