### ISSUE TITLE
IBM, IOUP, Matern

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#314]
IOUP, Matern, and IBM, are not really IBM (and the others, respectively), but *M* such processes in a joint SDE model. This is what the `spatialdim` in the inits means, though admittedly, this variable is not very aptly named. 

The class names and inputs need to reflect this. Maybe something along the lines of `TensorMatern`, `TensorIBM`, etc., with a parameter `num_copies` or so? Alternatively `VectorMatern`, `VectorIBM`, ...?

**Comment by schmidtjonathan** [comment]
What do you think about a structure along these lines:
- We have an `Integrator` class, that is in itself scalar (`spatialdim` is removed altogether). `Matern`, `IBM`, etc. inherit from this
- We implement a `StackedIntegrator` class (the name is debatable, of course) that stacks independent processes in a single state vector. 
- Optionally, we can implement classes `Vector{IBM, Matern, etc.}` that inherit from `StackedIntegrator`

**Comment by pnkraemer** [comment]
I think stacking would forbid priors of the generality presented in https://arxiv.org/pdf/2004.00623.pdf. We are not there yet with the implementation, but this is where I want to head. 

Having the integrator with "spatialdim=1" seems reasonable though. If you have any other ideas, please go ahead and suggest sth :)
