### ISSUE TITLE
Break up large modules into smaller parts

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#32]
I suggest to break long modules (`randomvariable` has roughly 1600 LoC) into smaller modules: one for the randomvariable interface, one for the distribution interface, one for gaussian implementations, one for dirac implementations etc.. This, together with an __init__.py file containing something along the lines of `from . import *` will have both, an intuitive namespace (randvar.dirac, randvar.multivargaussian, ...) as well as easy-to-read and easy-to-find code.

**Comment by JonathanWenger** [comment]
I think breaking up large files into smaller ones is a good idea, however I would like to keep namespaces compact. As a user I find it much more convenient to call distribution functions that are all in the same namespace, e.g.
```
probnum.probability.Normal
probnum.probability.RandomVariable
```
Comparing this with `scipy.stats` and `numpy.random`, there everything is also in one namespace.

**Comment by pnkraemer** [comment]
That is what I meant, reading my message again I realised it wasnt formulated well :)

**Comment by JonathanWenger** [comment]
Broke up `distribution`, `linearoperators` and `linearsolvers` in a58e998.
