### ISSUE TITLE
Resolve circular dependencies between distributions

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#33]
The convenience function `asdist` and also distribution arithmetic causes circular dependencies between `Distribution`,  `Dirac` and `Normal` preventing them from being separated out into their own files.

Idea: Move `asdist` and `asrandvar` to the interface and remove `asdist` from arithmetic operations.

This issue arises from the goals of #32 .

**Comment by pnkraemer** [comment]
I think it is a good idea anyway to move `asdist` and `asrandvar` into the interface.py
