### ISSUE TITLE
probability.randomvariable review

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#34]
The below does not take into accout the shape and dtype of neither self nor other. Is that on purpose?

https://github.com/probabilistic-numerics/probnum/blob/5f420d78367752fd87b50c08cc50d413082ab032/src/probnum/probability/random_variable.py#L212

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L48

is there a setting in which a randomvariable does not have a distribution? If not, I wouldnt set `distribution=None`.

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L50

This comment isnt adding any value IMO.

Btw: I hope you don't find the reviews petty. Everything is obv. up for discussion, I am just saying the first thing that comes to my mind :)

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L51-L62
Seems to me that if `dtype` is `None`, there is no self._dtype set. Is that true? (Desired?)

Would it have the same effect to write:
```python
if distribution is not None:
    self._dtype = distribution.dtype
elif dtype is not None:
    self._dtype = np.dtype(dtype)
else:
   raise ValueError("dtype not set.") 
```

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L64-L75

The same comments apply to the `self._shape` as well (as far as I understand)

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L90

We should set some type of __repr__ implementation in stone. I like your implementation. So far I have always tried to represent an object by the way to initialise, e.g.:
```python
print(rv)    # returns: RandomVariable(shape=(2,), dtype='int', distribution=Dirac(1.0))
```
but that is probably not feasible for everything and I don't really mind, honestly.

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L48-L83

Also if my comments above are wrong, I think there is value in tidying up this function. E.g., as you say in the comment below, by extracting methods `self._set_dtype(...)`,  `self._set_shape(...)` and `self._set_distribution(...)`.

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L102-L103

I like that you catch the `KeyError` and turn it into a `NotImplementedError`. I would have not been bothered to do it but your way is much better.

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L107

Another thing to but into the style guide: `cov` vs. `covar` as an abbreviation for covariances.

... and what shall one do about naming variances? `var` seems off here. Luckily I usually need covariances, so I never had to decide :)

**Comment by pnkraemer** [comment]
I dont get the `RandomState` thing but that is probably on me. Nothing to complain about in the code.

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L143-L160

Is there anything the distribution can do that the random variable cant, at least, pretend to be able to do? If yes, we have to be careful documenting these differences as it seems like `RandomVariable` wraps everything (I say that without having taken a closer look at the `Distribution` class).

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L175-L179

I would remove the comments as the code says more than a comment could here. Also, I would swap these actions as the self._distribution.reshape() might fail in which case we don't want the `RandomVariable` object to have set a new shape.

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L183-L187

An example of useful comments! Without the comment I would've been fairly confused what this line does :)

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L189

This is petty, but I have a strong feeling that changing the name to `_rv_from_binary_operation` would've saved me at least 3 scroll-up-and-back-down actions :)

Also, what is binary on this action?

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L227

To me, personally, that comment was more confusing than helpful. It might be because I know what _radd__ does and that I have to think twice to understanding the logic behind "reversed operands"  but either way, I dont think these kinds of comments (should) survive for long, anyway.

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L252-L270

Again, I might be alone with that opinion, but I hate (!) to write `blurgh += 1` in python and never use it (bold statement, I know, but I stand firmly). Also, is that even used for anything but indices in a loop? Maybe this piece of code can just be taken out, unless there are definite plans to implement these methods in the future :)

**Comment by pnkraemer** [comment]
https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L229

This takes care of adding scalars or matrices or such to random variables? If not, then we should find a way to do that (or to raise according errors). If yes, than some type-checking should be done here, e.g. whether the shape of the added array matches the shape of the random variable.

**Comment by pnkraemer** [comment]
In general: well done here, @JonathanWenger!

**Comment by JonathanWenger** [comment]
> https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L189
> 
> This is petty, but I have a strong feeling that changing the name to `_rv_from_binary_operation` would've saved me at least 3 scroll-up-and-back-down actions :)
> 
> Also, what is binary on this action?

✅  Binary refers to having two arguments (in this case random variables).

> https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L175-L179
> 
> I would remove the comments as the code says more than a comment could here. Also, I would swap these actions as the self._distribution.reshape() might fail in which case we don't want the `RandomVariable` object to have set a new shape.

✅ 



> https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L107
> 
> Another thing to but into the style guide: `cov` vs. `covar` as an abbreviation for covariances.
> 
> ... and what shall one do about naming variances? `var` seems off here. Luckily I usually need covariances, so I never had to decide :)

I suggest `cov` to conform to `numpy` and `scipy`.

> https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L143-L160
> 
> Is there anything the distribution can do that the random variable cant, at least, pretend to be able to do? If yes, we have to be careful documenting these differences as it seems like `RandomVariable` wraps everything (I say that without having taken a closer look at the `Distribution` class).

This came up again when refactoring and removing circular dependencies between `RandomVariable` and subclasses of `Distribution`. Now in terms of arithmetic random variables behave like `np.array` as much as possible, while distributions can only implement binary operations with other distributions.

**Comment by JonathanWenger** [comment]
> The below does not take into accout the shape and dtype of neither self nor other. Is that on purpose?
> 
> https://github.com/probabilistic-numerics/probnum/blob/5f420d78367752fd87b50c08cc50d413082ab032/src/probnum/probability/random_variable.py#L212

Yes, this is taken care of in the initialization of `RandomVariable` by taking the `dtype` of the combined `Distribution`.

> https://github.com/probabilistic-numerics/probnum/blob/d0a953fd36121cd7ea73d1b976a743de223afcdc/src/probnum/probability.py#L51-L62
> 
> Seems to me that if `dtype` is `None`, there is no self._dtype set. Is that true? (Desired?)
> 
> Would it have the same effect to write:
> 
> ```python
> if distribution is not None:
>     self._dtype = distribution.dtype
> elif dtype is not None:
>     self._dtype = np.dtype(dtype)
> else:
>    raise ValueError("dtype not set.") 
> ```

this is not the same due to the behaviour of `np.dtype` and the corner case where distribution and rv have different `dtypes`.
