### ISSUE TITLE
Nonlinear SDE and DiscreteGaussian

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#341]
Would be a useful feature if the non-linear Transition objects (``SDE``, ``DiscreteGaussian``) had some sort of state-dependency in the transitions. This is an even more general setup than currently.

**Comment by pnkraemer** [comment]
Admittedly, the message above is a bit cryptic. What is actually meant is that we want state-dependencies in the diffusions (aka covariances). Mostly, because the maths is sufficiently general and we are restricting ourselves unnecessarily.

**Comment by JonathanWenger** [comment]
> Admittedly, the message above is a bit cryptic. What is actually meant is that we want state-dependencies in the diffusions (aka covariances). Mostly, because the maths is sufficiently general and we are restricting ourselves unnecessarily.

Do you need this for a specific application at this point? If yes can you describe the use case in more detail, maybe with an example code snippet.

**Comment by JonathanWenger** [comment]
Closing this due to no concrete way forward. Feel free to add information and reopen.
