### ISSUE TITLE
Continuous-time smoothing.

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#343]
We are lacking a continuous-time smoothing implementation (Algo. 10.32ff in https://users.aalto.fi/~ssarkka/pub/sde_book.pdf).

To fix this shortcoming, the following hints could be useful:

* Look at how `DiscreteLinearGaussian` handles different forward (prediction) and backward (smoothing) implementations via strings and the methods `_forward_rv_classic`, `_backward_rv_classic`, `_backward_rv_sqrt`. The same shall be replicated in `LinearSDE`.
* Look at how the stage is set for different kinds of forward and backward implementations in `LinearSDE` (`_solve_mde_forward`). Here, we would like an implementation along the lines of `_solve_mde_backward` which implements the continuous-time RTS smoother (Algo 10.32 in https://users.aalto.fi/~ssarkka/pub/sde_book.pdf). 
* Continuous-time extended and unscented Kalman smoothing will need some more thought (type I and type II smoothers). This implementation might have to happen in `ContinuousUKFComponent` and `ContinuousEKFComponent`, but care should be taken to avoid code duplication.

**Comment by jzenn** [comment]
Hi @pnkraemer,
I have been looking into this issue. Does this issue include Type I and Type II smoothers (e.g. Algorithm 10.35 in the SDE Book) or did you only mean `_solve_mde_backward` in `LinearSDE`?

**Comment by pnkraemer** [comment]
Hey, thanks for looking into it! :) 

I suggest to do small increments and start with `_solve_mde_backward` in `LinearSDE`. We can always do more afterwards :) 

Type I and II are an EKF (and UKF) thing, which might require some design decisions that are not as obvious as for the simple continuous RTS smoother for `LinearSDE`. What do you think?

**Comment by jzenn** [comment]
Hi, sounds good to me :) I'd've suggested the same thing to get some feedback as soon as possible.

**Comment by jzenn** [comment]
#364 adds `_solve_mde_backward` in `LinearSDE`
