### ISSUE TITLE
Dispatch in transitions? 

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#345]
I recently found out that it is possible in python to dispatch on argument types (see "singledispatch" in functools: https://docs.python.org/3/library/functools.html).
Is that something for `Transition` objects? It could allow a generic `forward()` and `backward()` method that dispatches on the type of input being an array or a RV. `forward_realization`, etc., could still exist. 

Is that something useful? It seems fun to me, but I am afraid that it might not add benefit? I am also not entirely sure about the internal use-case, or whether it is only interesting for an outside interface. 

@schmidtjonathan @nathanaelbosch

**Comment by nathanaelbosch** [comment]
As someone that loves Julia's multiple dispatch, of course that looks very nice to me ;) I'm just a bit unsure about how readable / understandable the resulting code would be for most Python programmers.

**Comment by schmidtjonathan** [comment]
I wasn't aware of this, but at first sight it seems quite elegant. 👍 
As for readability, this would only concern contributors that make low level changes to the code, right? Otherwise it should be documented well :)

**Comment by pnkraemer** [comment]
I think readibility will not be an issue, as we can keep the names `forward_realization` etc. and use those in place of the `def _(arg,...) ` in the functools examples.

**Comment by nathanaelbosch** [comment]
I was mostly thinking about it being unusual, or maybe even bad practice, that functions behave differently depending on the input type. So "understandable" meant that a potential user / contributor might be surprised, if `forward(realization)` and `forward(rv)` return different objects. But I couldn't find anything on this in the google style guide, so that might also not be an issue at all :)

**Comment by pnkraemer** [comment]
Ah I see, thanks for clarifying :)  But do they return different objects? The return type is always `Tuple[RandomVariable, Dict]`.

**Comment by JonathanWenger** [comment]
> Is that something useful? It seems fun to me, but I am afraid that it might not add benefit? I am also not entirely sure about the internal use-case, or whether it is only interesting for an outside interface.

Since this has gone stale, I will close for now. Please re-open if still relevant.
