### ISSUE TITLE
Encapsulate GPy dependency

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#35]
(Reminder to rethink the GPy dependency.)

At the moment it is automatically installed at the first `pip install .`

**Comment by pnkraemer** [comment]
apparently, `decorator` and `paramz` are dependencies as well

**Comment by JonathanWenger** [comment]
I absolutely agree. Just a note: `decorator` and `paramz` arise from dependency on `GPy`.

**Comment by JonathanWenger** [comment]
Decision from PN Software Interest Group:
- need integration of GP framework via dependency
- write wrapper class `GaussianProcess(RandomProcess)`, so that implementation (and dependency can be swapped out if necessary)
