### ISSUE TITLE
Pylint for Quad

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#350]
**Decision from the meeting:**
Remove `pylint` ignores for `quad` subpackage to ensure a clean module. Most other packages are now essentially pylint-clean.

**Comment by JonathanWenger** [comment]
This would be best to do as part of your PR @alpiges. We can chat on how to do this, but in a nutshell the ignores for the `quad` module should be removed in `tox.ini` and then no accidental pylint issues are introduced.
