### ISSUE TITLE
module naming

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#36]
I propose to rename some modules, among others: `random_variable.py` into `randomvariable.py`.  I find it more convenient to have very few underscores. Apart from that it is in Pep8 (https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

**Comment by JonathanWenger** [comment]
In accordance with the above here would be my suggestions:

Modules that are in the namespace have _lowercase, shortened_ names:
```
- diffeq
- filtsmooth
- integ / quad
- linalg
    - linops
- optim
- prob
```
All other folders and files are _lowercase unless underscores improve readability_ (this is PEP8), i.e. `linearsolvers.py`, `bayesquadrature.py`, `randomvariable.py`.

I would also be okay with more expressive namespaces if the names are sufficiently short, i.e.
```
- diffeqns
- filtersmooth
- integrate
- linearalgebra
    - linearoperators
- optimize
- probability
```
or some combination of the two.

**Comment by pnkraemer** [comment]
I like the first version better!

**Comment by JonathanWenger** [comment]
Changed in 12bec47f67ecf8fdf3725179bdd61fd843ea80a0.
