### ISSUE TITLE
Module level documentation/READMEs

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#37]
I think it would be lovely to have a README for each module: probability, linalg, filtsmooth, .... I propose that as soon as we are "done" with each module, we hack up a quick readme with an example, some references and so on. I can do that and "practice" this way, to write readmes similar to yours :)

**Comment by JonathanWenger** [comment]
Is there an advantage of having this in the modules and not in the documentation or under the  example/development pages of the website?

**Comment by pnkraemer** [comment]
Doesnt having this in the modules lead to having it in the documentation?

**Comment by JonathanWenger** [comment]
Not if it is in a `README.md` unless we explicitly build sites for it in the documentation. There is two options for what you are describing.

1. Write this summary in the `__init__.py` file of the corresponding module, i.e. `probnum.prob`
2. Write directly into the documentation `rst` files under `docs/source/diffeq`
2. Write a long-form documentation similar to the example notebooks in the documentation

I assume solution 1. is a good one for now and one can directly write in docstring format. I wrote a draft in `probnum.prob.__init__.py` in 50ebb7d.

<img width="989" alt="Screenshot 2020-04-03 at 16 07 04" src="https://user-images.githubusercontent.com/29815984/78369334-4d0e2080-75c5-11ea-96e7-88f98bc6d13a.png">

**Comment by JonathanWenger** [comment]
Current practice is a combination of options 1 and 3 above.
