### ISSUE TITLE
Dimensions of random variables

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#39]
https://github.com/probabilistic-numerics/probnum/blob/9a4e6cf4aee888ad447fe4228e576c7284aa90dd/src/probnum/probability/distribution.py#L527-L528

One thing that might be useful to think about is whether we restrict Diracs, Gaussians, etc. to be supported on (d,) arrays and make scalars etc. raise errors. Everybody can transform a scalar into an array, but it is more convenient to work with numpy arrays only (we can then use operations like @ and others).

_Originally posted by @pnkraemer in https://github.com/probabilistic-numerics/probnum/issues/38#issuecomment-608270253_

**Comment by JonathanWenger** [comment]
This is also relevant for linear solvers #18.

**Comment by JonathanWenger** [comment]
Result from discussion:
- The user should be able to pass floats or arrays of all sizes [(), (n,), (n,n), ...]
- Internally everything is done in a vectorized manner with `np.array`
- In the case where efficient implementations for floats exist, i.e. (`UnivariateNormal`) this does **not** apply

**Comment by pnkraemer** [comment]
Great, thanks! 

Any opinion about making `_Univariate`, `_Multivariate`, etc. public? We'd keep the `Normal` facade, but allow more specific choices. I am not sure whether that is a good idea, would like to hear your opinion.

**Comment by JonathanWenger** [comment]
Could go either way. As a general rule I would err on the side of only having the most necessary classes public.
