### ISSUE TITLE
Settings as context managers

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#399]
# Current State and Problem
No package wide settings exist leading to local definitions and switches of variables such as `jitter`, `damping`, etc.

## Use Cases
see below for some examples

# To Do
- [ ] Create a `probnum.settings` module which collects context managers that let you set settings for a code segment.
- [ ] Write a context manager class for settings (see for example [`gpytorch.settings`](https://docs.gpytorch.ai/en/v1.1.1/settings.html))
- [ ] Settings for specific modules should be under `probnum.settings.linalg` or `probnum.settings.filters`

```python
from probnum import settings

with settngs.fast_computations():
     probsolve_ivp(...)
```

Don't start with overly general settings! Only implement what you actually use (in more than one place)

**Comment by mmahsereci** [comment]
Which is the concrete use case of this change? Are the related methods already implemented or is it related to an open PR? Can someone please add it here for documentation? Thanks!

**Comment by JonathanWenger** [comment]
@schmidtjonathan Could you add a short draft snippet which illustrates the use case you mentioned for filters? Thanks!

**Comment by schmidtjonathan** [comment]
Sure! For Kalman filtering and smoothing, probnum provides - besides the `classic` implementation - a square-root (`sqrt`) implementation that - roughly speaking - uses the Cholesky factors of the covariances for the computations. This takes a bit longer but can be numerically more stable.

The type of implementation (`sqrt`/ `classic`) is provided when creating the transitions. So, when creating multiple transitions:

```python
forward_implementation = args.pn_forward_implementation
backward_implementation = args.pn_backward_implementation

dynamics_process = pnss.IBM(
    # some kwargs, ...
    forward_implementation=forward_implementation,
    backward_implementation=backward_implementation,
)

measurement_model_data = pnss.DiscreteLTIGaussian(
     # some kwargs, ...
    forward_implementation=forward_implementation,
    backward_implementation=backward_implementation,
)
```

We thought that something like this might be less error prone while reducing complexity:

```python

with probnum.cfg.filtsmooth.use_sqrt_implementation():
# or probnum.cfg.filtsmooth.use_implementation(forward="sqrt", backward="sqrt")
# or probnum.cfg.filtsmooth.slow_but_stable():
# ... 
  dynamics_process = pnss.IBM(
      # some kwargs, ...
  )
  
  measurement_model_data = pnss.DiscreteLTIGaussian(
       # some kwargs, ...
  )
```

**Comment by pnkraemer** [comment]
see also the third todo in #335

**Comment by pnkraemer** [comment]
It seems that the common denominator for these two use cases is propagating Cholesky factors through a sequence of computation.Thus, why not name this setting `propagate_cholesky_factors()` (or rather `dont_propagate_cholesky_factors()` I guess, because I suppose a better default is to do it?). Thoughs, guys?

**Comment by JonathanWenger** [comment]
I suggest
```python
with cfg.cholesky_factors(propagate=True)
    ....
```

**Comment by JonathanWenger** [comment]
Another settings context we may want, which is quite general is a switch between lazy computations via linear operators for large-scale problems and in place operations on dense arrays. This constitutes a trade-off between memory and speed. So maybe something like

```python
cfg.lazy_computations(on=True)
cfg.fast_computations(lazy=True)
...
```

**Comment by pnkraemer** [comment]
In case anyone is interested: I am currently doing a test run of this in probnum-evaluation, where one can change settings of how to solve linear systems with covariance matrices with a context manager (e.g. switch between Cholesky, solve, and pseudo-inverse, or add custom damping). If you know how to improve my implementation, please let me know.

Code: https://github.com/probabilistic-numerics/probnum-evaluation/blob/main/src/probnumeval/config.py
Usage: have a look at the notebook https://probnum-evaluation.readthedocs.io/en/latest/tutorials/measure_error_and_calibration.html, or at the tests for the context manager https://github.com/probabilistic-numerics/probnum-evaluation/blob/main/tests/test_config.py
