### ISSUE TITLE
ProbNum Landing Page

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#400]
Alternatively we should also be able to host the `readthedocs` site at `probnum.org`.

**Comment by philipphennig** [comment]
I wrote to Mike Osborne. He's happy to change http://probnum.org to point to wherever we want. 

Incidentally, if we want we can also update http://probabilistic-numerics.org itself. It's obviously outdated. It would be good to keep both the workshop websites and the literature collection on there. If anyone is keen to build a new website (after NeurIPS ;), please let me know.

**Comment by JonathanWenger** [comment]
Great. Let's have https://probnum.readthedocs.io/ point to https://probnum.org for now and after NeurIPS we can build a new landing page.

**Comment by pnkraemer** [comment]
Sounds great!

**Comment by philipphennig** [comment]
Let's re-connect after the NeurIPS deadline and finalise this move.

**Comment by JonathanWenger** [comment]
Here's a way to add a custom landing page to our current setup with sphinx: https://ofosos.org/2018/12/28/landing-page-template/
