### ISSUE TITLE
Rename branch: master -> main 

### ISSUE THREAD

**Issue by mmahsereci** [probabilistic-numerics/probnum#402]
# Problem
Community standards of GitHub suggest the main branch should be called `main` instead of `master`.

# To Do
- [ ] Rename `master` to `main`: https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch
- [x] Update Github Action in `probabilistic-numerics/probnum-benchmarks-runner`

# Note
This requires everybody with a local fork of `probabilistic-numerics/probnum` has to update the upstream branch or pull `main`.

**Comment by mmahsereci** [comment]
Locally, run the commands below. Replace `origin` with your name of the ProbNum remote. This may for example also be `probnum` or `upstream`. You can check the name of your remote by running `git remote -v` in the command line.


```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by JonathanWenger** [comment]
Be careful if executing these commands to not accidentally change the remote of your local `main` branch to `upstream` instead of `origin`.
