### ISSUE TITLE
Input parameters of ODE-interpolation 

### ISSUE THREAD

**Issue by NinaEffenberger** [probabilistic-numerics/probnum#416]
Currently interpolation in `timeseriesposterior` and its subclasses is performed with:
```
def interpolate(
        self,
        t: FloatArgType,
        previous_location: Optional[FloatArgType] = None,
        previous_state: Optional[randvars.RandomVariable] = None,
        next_location: Optional[FloatArgType] = None,
        next_state: Optional[randvars.RandomVariable] = None,
    ):
```
E.g. `PerturbedStepSolver` also needs the index of `previous_location`.  It would therefore be useful to pass this index `index_previous`, too.

**Comment by pnkraemer** [comment]
This is already handled in #352. Once this is merged, that problem will be solved.

**Comment by JonathanWenger** [comment]
> This is already handled in #352. Once this is merged, that problem will be solved.

@NinaEffenberger can this be closed in light of the above?
