### ISSUE TITLE
Is instance variable `self._mean` needed in `Normal`?

### ISSUE THREAD

**Issue by mmahsereci** [probabilistic-numerics/probnum#421]
or can it be replaced by `self.mean` in all methods?

`self._mean` is defined [here](https://github.com/probabilistic-numerics/probnum/blob/master/src/probnum/randvars/_normal.py#L120), but I am wondering if it is needed at all, as there is also the cached property `self.mean` from the parent class. Same question for `self._cov` (L121)

**Comment by mmahsereci** [comment]
@JonathanWenger mentioned @marvinpfoertner may have the answer to this.

**Comment by marvinpfoertner** [comment]
Yes we can get rid of it. To be honest, I don't really know why this is even there. Might be a legacy artifact from the old design of `NormalDistribution` that I missed.
