### ISSUE TITLE
Package structure (`statespace`, `randprocs`, `filtsmooth`)

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#436]
**Problem**
The three subpackages `statespace`, `filtsmooth` and `randprocs.MarkovProcess` have unclear or convoluted interdependencies.

**To Do:**
- [ ] Visualize and understand reasons behind the current dependency structure
- [ ] Design desired dependency structure with an aim to decohere current modules
- [ ] Document new structure in the documentation
- [ ] Create issues for refactoring accordingly (e.g. move classes / methods from `statespace` into `randprocs`)

**Comment by pnkraemer** [comment]
The structure at the moment is

statespace

|                      \
v                      v
randprocs -> filtsmooth

Maybe this also relates to the most recent discussion?
