### ISSUE TITLE
Create a class RandomProcess

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#44]
Create a module `randomprocesses` analoguosly to `randomvariables`. This module should contain a super class `RandomProcesses` with functions like `meanfunction` and `covfunction`.

Classes from `statespace` will inherit from `RandomProcesses` as well as future implementations (or wrappers) of Gaussian processes.

**Comment by JonathanWenger** [comment]
Mocked up in 6be4468.

**Comment by pnkraemer** [comment]
We should be careful as to whether randomprocesses are just gaussian processes or not. If not, the mean and covariance structures are a lot less apparent. Also, it will make a big difference implementation-wise, how each random process is defined (e.g. as a collection of RVs vs. as solutions to SDEs).
