### ISSUE TITLE
diffeq.probsolve_ivp expects tfirst=True, breaking scipy 1.1.0 drop-in compatibility

### ISSUE THREAD

**Issue by philipphennig** [probabilistic-numerics/probnum#449]
Hi all, 

I'm mostly filing this to gain some experience with the process on here. 

I tried solving an ODE today to make a quick plot. I had code to produce a solution with `scipy.integrate.odeint`, so I thought I could just drop the same call into `diffeq.probsolve_ivp`. But this didn't work. Took me a few minutes, but the issue is that, by default since scipy version 1.1.0, `odeint` expected the vector field as `f(y,t)` (it has an optional argument `tfirst=True` to switch the order around, but the default is `False`). Meanwhile, `pn` expects `f(t,y)`. 

**System:**
I'm on `main`, version `0.1.8`, and on scipy `1.6.3`, numpy `1.21.0`. 

Not sure what the right way to fix this is. One option is to switch the order to be compatible with scipy; but I assume you have a reason for this order. Another option would be to add a `tfirst` option and explain in the doc that it's True by default.

Yay, my first bug report!

**Comment by mmahsereci** [comment]
Thanks, @philipphennig :) :1st_place_medal:  . Would you be able to post a self-contained minimal code snipped in this thread, for us to be able to reproduce the bug. This will help us understand the problem faster.

**Comment by pnkraemer** [comment]
`probsolve_ivp` is a drop-in for `scipy.integrate.solve_ivp`. As far as I know, `odeint` is not the thing to use anymore; the docs of `odeint` say:

```
For new code, use scipy.integrate.solve_ivp to solve a differential equation.
```

Can you please check whether your code works with `solve_ivp`? 

In any case, thanks for the report. Please don't hesitate to post more issues! :)

**Comment by philipphennig** [comment]
Ah! That’s great. Evidently, *I* need to upgrade my interface. 

Thanks!

Philipp

**Comment by pnkraemer** [comment]
seems like this can be closed. Please reopen if the issue is not solved.

**Comment by philipphennig** [comment]
Yes, it can. Thanks!

P
