### ISSUE TITLE
Code Review: Quadrature

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#45]
```python
    def __init__(self, nodes, weights, bounds):
        """
        Create an instance of a quadrature method.
        """
        utils.assert_is_2d_ndarray(nodes)
        utils.assert_is_1d_ndarray(weights)
        utils.assert_is_2d_ndarray(bounds)
        if len(nodes) != len(weights) or len(nodes.T) != len(bounds):
            raise ValueError("Either nodes and weights or nodes and bounds are incompatible.")
        self.nodes = nodes
        self.weights = weights
        self.bounds = bounds
        super().__init__()
```
I think it might make sense to move the bounds out of `__init__` so one can instantiate a quadrature methods with its parameters and then call `qm.integrate(func, bounds)` multiple times. Otherwise one has to instantiate the class every time the integrand or bounds change.

```python
def _compute_weights_1d(npts, ndim, ilbds1d):
    """
    """
    if npts % 2 == 0:
        raise ValueError("Please enter odd npts")
    nhalfpts = int((npts + 1.0) / 2.0)
    ind_j = 2.0 * np.arange(1, nhalfpts + 1) - 1.0
    ind_i = np.arange(1, npts + 1)
    arr1 = 2.0 / (npts + 1.0) * np.sin(ind_i * np.pi / (npts + 1.0))
    arr2 = 1.0 / ind_j
    arr3 = np.sin(np.outer(ind_j, ind_i) * np.pi / (npts + 1.0))
    weights = arr1 * (arr2 @ arr3)
    return (ilbds1d[1] - ilbds1d[0]) * weights
```
You already mentioned this, so this is just a reminder, the code can be kind of hard to read without comments in with shortened variable names (e.g. `ilbds`).

```python
class Quadrature(abc.ABC):
    """
    An abstract base class for Quadrature methods.

    This class is designed to be subclassed by quadrature implementations.
    """

    def __init__(self):
        """
        """

    def integrate(self, func, **kwargs):
        """
        Numerically integrate the given function.

        Parameters
        ----------
        func : function
            Function to be integrated.
        kwargs

        Returns
        -------

        """
        raise NotImplementedError
```
I refactored the `quad` module to pull everything under the same abstract `Quadrature` class (see above). I think it makes sense to expand the signature of `integrate` to `integrate(func, domain, **kwargs)`. This also relates to the first comment.

Needs decision: Naming of the function to be integrated: `fun`, `func`, `fct`, `integrand`, ...?

**Comment by pnkraemer** [comment]
I agree with the proposals. However, I think it would solve most of the problems of documentation if somewhere I write that `ilbds` refers to `integralbounds`. But yeah, there surely are ways to make it more readable.

Regarding the naming: I would have picked `integrand` for truth-reasons, however, in the past I found that it is hard to distinguish the words `integrate` and `integrand` when reading the code. So maybe we should use `fun`, because afterall, who doesn't like a bit of fun? ;)

**Comment by pnkraemer** [comment]
Reminder to myself: make use of the new `ClenshawCurtis` structure in `statespace/continuous/linearsde/`.

**Comment by pnkraemer** [comment]
Reminder to myself: ignore the previous reminder to myself as it is outdated by now :)
