### ISSUE TITLE
Webpage shows old version

### ISSUE THREAD

**Issue by mmahsereci** [probabilistic-numerics/probnum#467]
**Describe the bug**
Website does not show the updated pages after PR #462 . For example [this](https://probnum.readthedocs.io/en/latest/development/pull_request.html) page still shows the version with "master" instead of "main" branch.

**To Reproduce**
click on docs link

**Expected behavior**
Expceted to see the updated webpage.

**System:**
na

**Additional context**
related to #462

**Comment by JonathanWenger** [comment]
This may be caused by the use of permalinks vs actual links. Will investigate in the morning.

**Comment by JonathanWenger** [comment]
This was caused by the default configuration of ReadTheDocs pointing to `master` and the docs build failing. I changed this to `main` now and re-built `latest`. Now the Docs actually show the changes made in #462.
