### ISSUE TITLE
Check for closed form solutions in state space models

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#48]
For some state space models where quadrature (`ClenshawCurtis`) is used currently, closed forms solutions (might) exist in the literature.

**Comment by pnkraemer** [comment]
Was just about to post the same... thanks! Will be corrected soon.

**Comment by pnkraemer** [comment]
Resolved in 487024d7c3d61de831ce554d460b8e213d0deb04
