### ISSUE TITLE
Visual tests and doctests

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#49]
Some tests and doctests currently generate plots. This is a difficult test as it requires human input and therefore cannot be tested by the build tool. Further plotting tests seem to run quite slow compared to the other tests.

We should try to replace plotting tests with regular tests checking the same idea (numerically) if possible.

**Comment by pnkraemer** [comment]
Should be resolved in 

487024d7c3d61de831ce554d460b8e213d0deb04
