### ISSUE TITLE
n-dimensional integration using `bayesquad`

### ISSUE THREAD

**Issue by mmahsereci** [probabilistic-numerics/probnum#513]
### Discussed in https://github.com/probabilistic-numerics/probnum/discussions/512

<div type='discussions-op-text'>

<sup>Originally posted by **gerdm** August  8, 2021</sup>
Hi,

I've been trying to use `probnum`'s  `bayesquad` function to integrate a vector-valued function. However, I cannot get it to work. Here's a small example

```python
from probnum.quad import bayesquad

def f(x):
    return x.T @ x

domain=jnp.array([-3, 3])
bayesquad(f, 2, domain=domain)
```

but I get the following error

```python
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 50)
```

I've tried different different domain configurations, but they do not work either.

```python
domain = np.array([
[-3, 3],
[-3, 3]
])

domain = np.array([-3, 3, -3, 3])
```

How can I compute this integral?</div>

**Comment by mmahsereci** [comment]
Hi @gerdm , answering here instead of in the discussion section for better visibility. 

From what I can see the issue is with the function definition of f. Can you try using the following instead and let me know if that works?

```
def f(x):
    return np.sum(x **2, axis=1)
```

In essence, the code evaluates f in a batch. That is for a matrix of points `x` of shape (num_datapoint, input_dim) the function `f` needs to return a vector of shape (num_datapoint, ).  I noticed that this is not well documented in the docs of `baysquad`, so thanks for opening the issue.

**Comment by gerdm** [comment]
Thanks @mmahsereci!

Your example works.

**Comment by mmahsereci** [comment]
Great, thanks for the quick feedback @gerdm. Feel free to open another issue if you encounter further problems. Closing this one.
