### ISSUE TITLE
RandomVariable adapters

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#53]
**Half-cooked idea below**

What I'd find quite useful is having a few adapters that wrap distributions from e.g. scipy.stats or pyro into the shape that we use. This way we'd have to implement ourselves only what we heavily rely on (`Normal`, `Dirac`?) or what is not provided elsewhere (`OperatorvariateNormal`?).

Background story: for some sequential Monte Carlo I'd like to use some distributions other than Normal, and Dirac, and found that it would be very convenient to integrate e.g. Gamma distributions from scipy, etc. into our `RandomVariable` framework with functions like `scipy2distribution`, `pyro2distribution`, etc..

The same could even work for GPs: one abstract GP interface and adapters like `gpy2gp`, `gpytorch2gp`, `gpyflow2gp` which adapts the corresponding classes and makes them compatible. This way we would not implement any GP details but still have enough flexibility to do it wherever necessary.

I dont think these adapters would be a lot of work, but they might make life very convenient. I dont even think they would lead to dependencies (except for testing these functions of course).

*Thoughts?*

**Comment by pnkraemer** [comment]
Something along the lines of

```python
def scipy2dist(rvcont):
    """
    Transform a scipy.stats.rv_continuous object into a Distribution.

    Parameters
    ----------
    rvcont : scipy.stats.rv_continuous
        Random variable object to be transformed.

    Returns
    -------
    Distribution
        scipy.stats.rv_continuous object rvcont as a Distribution.
    """
    try:
        cov = rvcont.cov
    except AttributeError:
        cov = None
    parameters = {"var": rvcont.var}
    return Distribution(parameters=parameters,
                        pdf=rvcont.pdf, logpdf=rvcont.logpdf,
                        cdf=rvcont.cdf, logcdf=rvcont.logcdf,
                        sample=rvcont.rvs, mean=rvcont.mean,
                        cov=cov, dtype=None,
                        random_state=rvcont.random_state)
```

**Comment by JonathanWenger** [comment]
Did you take a look at `prob.asrandvar`? If i understand correctly that basically does what you are looking for with `scipy` distribtions. The problem with distributions or gp "adapters" is that they introduce dependencies on the corresponding packages.

I think here the clean way is to provide an abstract class which the user can subclass. Long-term I think we should have our own implementations of the main distributions anyway, even if they just wrap scipy functions - just for convenience.

**Comment by pnkraemer** [comment]
`asrandvar` does the trick, thanks.
