### ISSUE TITLE
asrandvar returns Distribution, not RandomVariable

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#55]
`asrandvar(scipy.stats.rv_continuous)` returns a Distribution object, not a RandomVariable.

I can resolve that, unless it is desired for some reason. Feel free to assign me :)

**Comment by JonathanWenger** [comment]
Oops good catch. That's a mistake. Fixing it right now.

**Comment by pnkraemer** [comment]
Okay, I could've done it. In the process of fixing some things now anyway. But seems like you want to do it yourself :)

**Comment by JonathanWenger** [comment]
Implemented in 44d84af615c9617d6d9e514d7ec259ea717bdd0a.
