### ISSUE TITLE
Replace some Jupyter notebooks in the Documentation with RST files

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#597]
**Is your feature request related to a problem? Please describe.**
Part of the documentation is written in `ipynb` files. This creates very large diffs and files that are checked into the repository.

**Give an example use case.**
The developer tutorial [Creating an Example Notebook](https://probnum.readthedocs.io/en/latest/development/creating_an_example_notebook.html) does not execute any code, but just loads a code snippet and therefore does not need to be a Jupyter notebook.

**Describe the solution you'd like.**
Replace Jupyter notebooks in the docs wherever possible with `.rst` files and include code with the Sphinx directive [`literalinclude`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude).

**Comment by DevPranjal** [comment]
Hello @JonathanWenger, I would like to work on this. Do I have to replace only those files where cells only load a code snippet (without any real output)? 

Also, I have been looking to participate in the upcoming GSoC. I find this a good opportunity to get introduced to the code base and the tutorials provided.

**Comment by JonathanWenger** [comment]
Great that you're interested in GSoC! 

> Do I have to replace only those files where cells only load a code snippet (without any real output)?

Exactly. Notebooks that do not actually _execute_ code can simply be replaced by `.rst` files. One challenge is to ensure that the thumbnails in the gallery can still be displayed (see https://probnum.readthedocs.io/en/latest/development/developer_guides.html) for an example of the gallery. Of the top of my head the following notebooks should be replacable:
- [ ] [unit_testing.ipynb](https://github.com/probabilistic-numerics/probnum/blob/main/docs/source/development/unit_testing.ipynb)
- [ ] [adding_to_the_api_documentation.ipynb](https://github.com/probabilistic-numerics/probnum/blob/main/docs/source/development/adding_to_the_api_documentation.ipynb)
- [ ] [creating_an_example_notebook.ipynb](https://github.com/probabilistic-numerics/probnum/blob/main/docs/source/development/creating_an_example_notebook.ipynb)

**Comment by DevPranjal** [comment]
Thanks for pointing out the notebooks.
> One challenge is to ensure that the thumbnails in the gallery can still be displayed (see https://probnum.readthedocs.io/en/latest/development/developer_guides.html) for an example of the gallery

I tried adding the image directly into the `.rst` file, but that did'nt render the thumbnail in the gallery. I'll explore more solutions.
