### ISSUE TITLE
Jupyter notebooks illustrating ODE solvers

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#60]
The examples section of the documentation should contain jupyter notebooks illustrating the usage of `probnum.diffeq`.

**Comment by pnkraemer** [comment]
@nathanaelbosch something like the plot in your presentation yesterday would be awesome. Can you do this? Further, I/we can do some convergence rate plots like in the papers (https://arxiv.org/pdf/1807.09737.pdf and https://arxiv.org/abs/2004.00623). Some scaffolding is already there, but I am not sure whether this refers to up-to-date versions...
