### ISSUE TITLE
Type Hints

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#61]
All internal classes and methods should have type hints (https://docs.python.org/3/library/typing.html). This prevents pesky type bugs. 

Example method with a `str` type hint:
```python
def greeting(name: str) -> str:
    return 'Hello ' + name
```

**Comment by pnkraemer** [comment]
Only the internal ones? Why not all visible ones? I would find it hard to distinguish purely internal functions from purely public functions but maybe I am not trying hard enough :)

**Comment by JonathanWenger** [comment]
Closing as this is now standard practice when accepting PRs and no longer an active TODO.
