### ISSUE TITLE
Replace all assert statements in the code with errors

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#62]
All assert statement in the code base should be replaced by a statement raising a corresponding error instead.

**Comment by mmahsereci** [comment]
some of the assert statements may also go once the shapes and types are well defined and tests are written for them

**Comment by nathanaelbosch** [comment]
Does this issue also include `assert` statements in the `./test` folder? In any case there seem to only be these two:
- `./tests/test_linalg/test_linearsolvers/test_linearsolvers.py:131`, and 
- `./tests/test_prob/test_distributions/test_normal.py:89`

**Comment by mmahsereci** [comment]
no, it does not include assert statements in tests. In tests, asserts are fine.

**Comment by pnkraemer** [comment]
We can close this one, no?

**Comment by JonathanWenger** [comment]
Fixed by #75
