### ISSUE TITLE
Package Structure Refactoring

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#63]
In order to avoid dependency bugs all modules (`diffeq`, `filtsmooth`, `optim`, `quad`, `linalg`) should not depend on each other but only on a central `core` folder which contains `prob` and `linops`. This way the modules are disentangled.

Do not keep around a `utils` folder as it just collects random classes and functions which should rather be in the corresponding modules.

Add an `examples` folder which contains unpolished implementations of PN methods (for example from papers) contributed by other researchers which might move into the core codebase in the future.

TODOs:
- [ ] ~create core folder and pull corresponding modules into it~
- [ ] ensure namespaces are still in line with the styleguide
- [ ] ~remove `utils` folder and move classes into corresponding modules~
- [ ] ~create `examples` folder~
- [ ] create a `probnum-contrib` repository

**Comment by nathanaelbosch** [comment]
Is the `examples` folder supposed to be outside of the package (i.e. `./examples/`) or inside of the package (e.g. `./src/probnum/examples/`)? Both could be valid approaches. I think the choice would depend on if we want to distribute these methods or if they rather serve as motivation, and even as part of the documentation.

**Comment by JonathanWenger** [comment]
**Decisions from Software Meeting**

- There exists a set of core subpackages (`random_variables`, `random_processes`, `kernels`, `linops`, ...) which all other subpackages implementing probabilistic numerical methods depend on.
- A subpackage `probnum.testproblems` contains standard problems or loaders one might try probabilistic linear solvers on. This is analogous to something like [`torchvision.datasets`](https://pytorch.org/docs/stable/torchvision/datasets.html)
- Instead of an `examples` folder a separate repository `probnum-contrib` will be created containing newly composed or implemented PN methods which may make their way into the main package in the long run. This would be analogous to [`pytorch/contrib`](https://github.com/pytorch/contrib). Making a contribution to this package has lower standards than ProbNum. This can also become the modus operandi of how papers are written introducing new PN methods: Invent method, code method, PR into `probnum-contrib`, code clean-up, PR into `probnum`.

**Comment by JonathanWenger** [comment]
Closing this as all immediate action items are implemented. If `probnum-contrib` becomes relevant at some point a new issue should be created.
