### ISSUE TITLE
Shape and type tests should exist for every (public) function

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#65]
Create tests checking in and output shapes for all PN methods and also the in and output types.

**Comment by mmahsereci** [comment]
output shapes, and dims you can write test. Not sure how you would write input shape tests. 

For input type/value tests I meant testing if an error is raised appropriately. E.g., if you raise an error for an input of a user, you can write a test that checks if the error is raised correctly.
