### ISSUE TITLE
`test_kernel_mean_matern_lebesgue_measure` is a bit flaky.

### ISSUE THREAD

**Issue by mmahsereci** [probabilistic-numerics/probnum#661]
**Describe the bug**
The test `test_kernel_mean_matern_lebesgue_measure` occasionally fails. It should be investigated why. 

Examples:
- https://github.com/probabilistic-numerics/probnum/runs/5539496853?check_suite_focus=true#step:5:24035
- https://github.com/probabilistic-numerics/probnum/runs/5500893583?check_suite_focus=true#step:5:23997

**Expected behavior**
Non-flaky test.

**Additional context**
The test tests an integral value which is notorious hard to test. In case the test uses an rng (I haven't checked yet), we should aim to avoid it. If it does not, I am quite unsure why the test fails occasionally.

**Comment by pnkraemer** [comment]
I just ran into this as well in https://github.com/pnkraemer/probnum/runs/6076169103?check_suite_focus=true

> In case the test uses an rng (I haven't checked yet), we should aim to avoid i

I think it does: the line
https://github.com/probabilistic-numerics/probnum/blob/b9a0a44bf101dfcc69289783ef5423991575932b/tests/test_quad/test_kernel_embeddings.py#L118
uses a default rng
https://github.com/probabilistic-numerics/probnum/blob/b9a0a44bf101dfcc69289783ef5423991575932b/src/probnum/quad/_integration_measures.py#L59
and thus becomes non-deterministic.
