### ISSUE TITLE
Matplotlib should not be a dependency

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#71]
Matplotlib should not be a dependency of the package. Only building the example notebooks requires matplotlib.

**Comment by JonathanWenger** [comment]
This is only a dependency of some tests in `probnum.diffeq`.

**Comment by nathanaelbosch** [comment]
GPy, per default, uses matplotlib. This dependency is in principle configurable (by modifying a local file `~/.config/GPy/user.cfg`), but I have the impression that this does not really lead to a clean solution. I propose that we keep an explicit dependency on matplotlib around until we manage to remove GPy from our dependencies. What do you think?

**Comment by pnkraemer** [comment]
Hmmmm I would agree, even though I am not the one whose opinion you wanted I guess :)

**Comment by JonathanWenger** [comment]
If matplotlib only gets installed due to GPy, then we can close this for now. This will then automatically be fixed by #35 .

**Comment by nathanaelbosch** [comment]
I believe #275 removed the matplotlib dependency so I'm closing this for now, though please re-open if I'm mistaken.
