### ISSUE TITLE
Tests in diffeq are failing for optimization methods

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#80]
Currently many tests for optimization methods in `probnum.optim` fail in the `diffeq` branch. This should be fixed so that proposed changes are built by Travis and properly tested.

**Comment by nathanaelbosch** [comment]
I'm looking into that right now, and I saw that there are some that should be easy to fix

**Comment by pnkraemer** [comment]
that is super weird, I don't remember touching anything there and the tests used to pass without complaints. Anyways, I will look into it.

**Comment by nathanaelbosch** [comment]
Don't worry for now @pnkraemer, I'm on it, I currently have the impression that the errors were introduced by my when I replaced the asserts, and that things should be easy to fix :)

**Comment by pnkraemer** [comment]
ah, maybe there used to be value errors for type checking and they are replaced with type errors or something now? If so, the tests might not be updated yet. But that is just a guess based on what you are saying...

**Comment by nathanaelbosch** [comment]
There is, if I'm not mistaken, only a single failing test left, on which I need a second opinion:

`./tests/test_optim/test_stoppingcriterion/test_stoppingcriterion.py:51`

The test calls `StoppingCriterion.create_unfulfilled(None)`, but does this even make sense? In a very similar test (same file, line 93), we first create an object `gooditer`, which we pass to `create_unfulfilled`. I guess we would need to do something similar in line 51.

**Comment by nathanaelbosch** [comment]
@pnkraemer the errors were more trivial, I just translated some of the conditions wrongly. But I guess that's what the tests are for :)

**Comment by pnkraemer** [comment]
how wonderful, all of that effort of writing those idiotic tests was worth something :tada:

**Comment by nathanaelbosch** [comment]
Alright! Looking through the files I found a fix that makes some sense to me, and all tests pass. I will open a PR and link this issue :+1:

**Comment by pnkraemer** [comment]
> The test calls StoppingCriterion.create_unfulfilled(None), but does this even make sense? In a very similar test (same file, line 93), we first create an object gooditer, which we pass to create_unfulfilled. I guess we would need to do something similar in line 51.

The stopping criterion in (context of line 51) works with the norm of the gradient: if that is small enough, the iteration is "converged". To create an iteration that violates this condition, you only initialise an iteration with gradient equal to infinity. 

The stopping criterion (in context of line 93) works with the difference of function values, and in order to create something that violates the condition you need the old value (i.e. `curriter`) which is different to the gradient norm one. For the sake of a unified interface, they both have curriter as an input, but the gradient iteration ignores it (hence, only a `None` is used in the test)

**Update (after reading your new message):** great, thanks for doing this nathanael!

**Comment by pnkraemer** [comment]
while we are at it: are you willing to do some renaming @nathanaelbosch? I stumbled about `fulfilled()` and `create_fulfilled()` which made it surprisingly hard to remember what happens. Maybe we change this to `is_satisfied()` and `create_violating_iteration/proposal()`? Shall I make this a new issue?

**Comment by nathanaelbosch** [comment]
I think it would be best not to mix up issues if we have the choice to separate them. At the current point, I also don't understand the different parts well enough, so I can't really give an opinion on the issue.

With your comment from above however, I think my "fix" is not really what we want. Basically, I added the creation of a `curriter`, but if indeed we want it to not take any input (see also the nice docstring at line 59 :D), then this might need a little more work. 

I'll still open a PR as a draft, to make my current changes more transparent.

**Comment by pnkraemer** [comment]
okay cool, assign me as a review for the PR and I can look into it
