### ISSUE TITLE
Overwrite mean and cov of distribution with parameter values if given?

### ISSUE THREAD

**Issue by marvinpfoertner** [probabilistic-numerics/probnum#82]
I feel like the `self._mean` should be overriden with

`self._mean = lambda: parameters["mean"] if "mean" in parameters else mean`.

https://github.com/probabilistic-numerics/probnum/blob/f13f26cf441e4182339faa2bc2b8347da77960c8/src/probnum/prob/distributions/distribution.py#L65-L75

**Comment by marvinpfoertner** [comment]
@JonathanWenger What's you take on this?

**Comment by nathanaelbosch** [comment]
Maybe a more general question: What is the `parameters` value used for?

Depending on that I would argue that we do not actually want two different ways to specify the mean and covariance.

**Comment by marvinpfoertner** [comment]
I agree, the `parameters` dict also makes it notoriously hard to implement slicing and masking for random variables.
Wouldn't it be better to put everything that is in `parameters` right now into members of the `Distribution`?
That way we avoid having unstructured members.

**Comment by JonathanWenger** [comment]
> I feel like the `self._mean` should be overriden with
> 
> `self._mean = lambda: parameters["mean"] if "mean" in parameters else mean`.
> 
> https://github.com/probabilistic-numerics/probnum/blob/f13f26cf441e4182339faa2bc2b8347da77960c8/src/probnum/prob/distributions/distribution.py#L65-L75

Yes. This should probably also throw a `ValueError` if mean is nonetheless specified.

> Maybe a more general question: What is the `parameters` value used for?
> 
> Depending on that I would argue that we do not actually want two different ways to specify the mean and covariance.

`parameters` contains the parameters of the distribution, (e.g. mean and covariance for the normal, shape and scale for the gamma, ...). So this is not necessarily the mean of the distribution. A subclass of distribution may not even implement `mean()` or `cov()` if they do not exist.

The reason why there is a way to specify `mean` and `parameters` was to allow arbitrary distributions to be defined without subclassing, e.g.
```python
mygammadist = Distribution(parameters={"shape":.1, "scale": .1}, mean=0.1)
```
The trouble with this is that if `parameters` is mutable, then inconsistencies arise. However we need to be able to construct arbitrary `Distribution` objects, e.g. for random variables where we only have a sampling method available.

**Comment by marvinpfoertner** [comment]
Ah I see. But would you still agree that, for the case of the mean parameter, where we have a "more structured" alternative (the mean method), we should not use the parameters dict?

IMHO the same would hold for the "support" parameter in the Dirac distribution. There we subclass anyway and it would feel just way cleaner if we just created a member "self._support" instead of storing the argument in the parameters dict.

**Comment by JonathanWenger** [comment]
I don't mind having members for the distribution parameters, but if you then don't (also) store them in the dict, that is pretty inconsistent with the super class definition,i.e. if a user reads the docs of `Distribution` and tries to inspect the parameters of a `Dirac`, those would be empty. I'm not sure what the cleanest solution is here.

**Comment by JonathanWenger** [comment]
One approach would be to remove the `parameters` dict and only allow custom parametrized `Distribution`s via subclassing. Any user defined distributions then do not have `parameters`.

**Comment by marvinpfoertner** [comment]
I like that proposal. However, I would not get rid of the `parameters` dict in the end.
It can still be useful as an unstructured datastore for the user-defined distributions.
I just wouldn't use it in the internal implementations of the (sub)class.

**Comment by JonathanWenger** [comment]
Okay so one can construct a `Distribution` by passing `parameters` but `parameters` is not a public member. Instead it is exposed in the following way in the super class:
```python
def get_parameters(self):
   return self._parameters
```
`Distribution` sub-classes can then create the dict in the `get_parameters` function.
