### ISSUE TITLE
Example jupyter notebooks should have identical default plotting parameters

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#85]
Create a matplotlib style file containing the plotting parameters or hide the first cell via JSON options. In particular the example notebooks on the website should not show the cell simply setting up plotting parameters (i.e. latex fonts & packages, pdf output, etc.)

**Comment by pnkraemer** [comment]
Stylefile I can take over. JSON no idea. Assign me if you like

**Comment by pnkraemer** [comment]
Okay as a quick follow up on what is possible: the `%matplotlib inline` stuff cannot be done in a stylefile and neither does the "setting default to svg". I am not sure whether it is actually important for those notebooks to do this. The plot styles (i.e. figure sizes, linewidths, colors, etc.) I have managed and will post an example/make a PR soon.

**Comment by JonathanWenger** [comment]
- `%matplotlib inline` ensures that plots are actually displayed as output in the notebook vs a pop-up or interactive plot. 
- set_matplotlib_formats('pdf', 'svg') forces plots to be vector graphics instead of pngs

Both are important for visually pleasing output and should be in the preamble of every notebook on the website (even if not in the stylefile).
