### ISSUE TITLE
array_like

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#89]
It seems that common input types are `array_like` and then we use them as` numpy.ndarrays`. Wouldn't it be good to have something like `np.asarray(array_like)` in the top parts of the functions?

**Comment by pnkraemer** [comment]
For instance, `Dirac` takes a support array_like but raises errors when the support is a list. This is only mildly inconvenient but perhaps something to keep in mind for future clean-ups

**Comment by JonathanWenger** [comment]
We have to decide whether we want to support `array_like`, which technically doesn't have a formal definition (see also https://stackoverflow.com/questions/40378427/numpy-formal-definition-of-array-like-objects). At least imo it should include sparse matrices. However a simple `np.asarray(array_like)` call is not enough. For example:
```python
import numpy as np
import scipy.sparse

I = scipy.sparse.identity(10)
np.asarray(I)
```
returns 
```
array(<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>, dtype=object)
```
We also wouldn't want a dense array here since that can cause memory issues for large sparse arrays.

**Comment by pnkraemer** [comment]
Yes I agree 100%. At the moment it says array like everywhere though without actually allowing array likes (I am aware this is not a very precise term but at least it should include lists and probably scalars which it doesn't always do currently). 

One foolproof, although potentially un-user-friendly solution would be to demand specific types, i.e. only ndarrays or sparse matrices or such and steer clear of the term array_like. I am not entirely sure what I think of this though.

**Comment by JonathanWenger** [comment]
I am in favor of that since it makes the term precise and if we use type hints, we have to do that anyway.

**Comment by pnkraemer** [comment]
I agree, especially in terms of sticking to the single-responsibility-principle (even though it will definitely bother me at some of those days when I am feeling a bit lazy). In any case, and if I remember correctly, we need to update lots of documentation torefactor this.

**Comment by pnkraemer** [comment]
Now numpy has a typing module which supports array like (and dtype): https://numpy.org/devdocs/reference/typing.html

**Comment by JonathanWenger** [comment]
This is partially superseded by the argument type `LinearOperatorArgType`, representing matrices or more generally, finite dimensional linear operators introduced in #460. 

Closing for now. Feel free to reopen.
