### ISSUE TITLE
_UnivariateGaussian should only be constructed for scalars

### ISSUE THREAD

**Issue by marvinpfoertner** [probabilistic-numerics/probnum#94]
IMHO a mean (and cov) with shape (1, 1) should construct a _MatrixVariateNormal and a mean with shape (1,) should construct a multivariate normal to be consistent with numpy. This would also make slicing much more intuitive.

https://github.com/probabilistic-numerics/probnum/blob/f13f26cf441e4182339faa2bc2b8347da77960c8/src/probnum/prob/distributions/normal.py#L271-L280

**Comment by nathanaelbosch** [comment]
Fixing this will break some tests in diffeq. This is a good thing! Ping me or @pnkraemer for help.

**Comment by marvinpfoertner** [comment]
Resolved by #135
