### ISSUE TITLE
Format code automatically for each pull request

### ISSUE THREAD

**Issue by JonathanWenger** [probabilistic-numerics/probnum#96]
Use a tool like `flake8` or `black` to enforce a consistent code format in the repository.

**Comment by marvinpfoertner** [comment]
I can strongly recommend black, but it is advisable to crank up the maximum line length to at least 100

**Comment by nathanaelbosch** [comment]
How does this issue compare to  #66?

As said there, I also strongly recommend black. However I am a fan of their 88 character line length, which already greatly relaxes the PEP8 limit to allow for two additional indents, but still enforces compact code.

**Comment by JonathanWenger** [comment]
Closing this as it is a duplicate of #66
